
package pogled;

import controller.Controller;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPanel;

/**
 *
 * @author Andrej
 */
public class GlavnaForma extends javax.swing.JFrame {

    private static JPanel selectedPanel = null;
    private CardLayout cardLayout;

    PanelProizvodi cardProizvodi;
    PanelKupci cardKupci;
    PanelLokaliteti cardLokaliteti;
    PanelOO cardOO;
    PanelGJ cardGJ;
    PanelKorisnici cardKorisnici;
    PanelMojNalog cardMojNalog;
    PanelRacuni cardRacuni;
    PanelOtpremnice cardOtpremnice;
    PanelAnaliza cardAnaliza;
    PanelOtpremaci cardOtpremaci;

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        inicijalizacija();
        setTitle("Glavna forma");
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelOtpremnice = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelRacuni = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanelAnaliza = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelLokaliteti = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanelGJ = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanelOO = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanelProizvodi = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanelKupci = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanelOtpremaci = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanelKorisnici = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanelMojNalog = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanelOdjavise = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 700));

        jPanelOtpremnice.setBackground(new java.awt.Color(0, 153, 51));
        jPanelOtpremnice.setPreferredSize(new java.awt.Dimension(200, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-note-30 (1).png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(40, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Otpremnice");

        javax.swing.GroupLayout jPanelOtpremniceLayout = new javax.swing.GroupLayout(jPanelOtpremnice);
        jPanelOtpremnice.setLayout(jPanelOtpremniceLayout);
        jPanelOtpremniceLayout.setHorizontalGroup(
            jPanelOtpremniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOtpremniceLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanelOtpremniceLayout.setVerticalGroup(
            jPanelOtpremniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOtpremniceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOtpremniceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        jPanel1.add(jPanelOtpremnice);

        jPanelRacuni.setBackground(new java.awt.Color(0, 153, 51));
        jPanelRacuni.setPreferredSize(new java.awt.Dimension(200, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-bill-30.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(40, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Računi");

        javax.swing.GroupLayout jPanelRacuniLayout = new javax.swing.GroupLayout(jPanelRacuni);
        jPanelRacuni.setLayout(jPanelRacuniLayout);
        jPanelRacuniLayout.setHorizontalGroup(
            jPanelRacuniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRacuniLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanelRacuniLayout.setVerticalGroup(
            jPanelRacuniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRacuniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRacuniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        jPanel1.add(jPanelRacuni);

        jPanelAnaliza.setBackground(new java.awt.Color(0, 153, 51));
        jPanelAnaliza.setPreferredSize(new java.awt.Dimension(200, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-analyze-30.png"))); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(40, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Analiza");

        javax.swing.GroupLayout jPanelAnalizaLayout = new javax.swing.GroupLayout(jPanelAnaliza);
        jPanelAnaliza.setLayout(jPanelAnalizaLayout);
        jPanelAnalizaLayout.setHorizontalGroup(
            jPanelAnalizaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnalizaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        jPanelAnalizaLayout.setVerticalGroup(
            jPanelAnalizaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAnalizaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAnalizaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        jPanel1.add(jPanelAnaliza);

        jPanelLokaliteti.setBackground(new java.awt.Color(0, 153, 51));
        jPanelLokaliteti.setPreferredSize(new java.awt.Dimension(200, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-location-24.png"))); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setPreferredSize(new java.awt.Dimension(40, 24));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lokaliteti");

        javax.swing.GroupLayout jPanelLokalitetiLayout = new javax.swing.GroupLayout(jPanelLokaliteti);
        jPanelLokaliteti.setLayout(jPanelLokalitetiLayout);
        jPanelLokalitetiLayout.setHorizontalGroup(
            jPanelLokalitetiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLokalitetiLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanelLokalitetiLayout.setVerticalGroup(
            jPanelLokalitetiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLokalitetiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLokalitetiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        jPanel1.add(jPanelLokaliteti);

        jPanelGJ.setBackground(new java.awt.Color(0, 153, 51));
        jPanelGJ.setPreferredSize(new java.awt.Dimension(200, 40));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-location-24.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(40, 24));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gazdinske jedinice");

        javax.swing.GroupLayout jPanelGJLayout = new javax.swing.GroupLayout(jPanelGJ);
        jPanelGJ.setLayout(jPanelGJLayout);
        jPanelGJLayout.setHorizontalGroup(
            jPanelGJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGJLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addContainerGap())
        );
        jPanelGJLayout.setVerticalGroup(
            jPanelGJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGJLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGJLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        jPanel1.add(jPanelGJ);

        jPanelOO.setBackground(new java.awt.Color(0, 153, 51));
        jPanelOO.setPreferredSize(new java.awt.Dimension(200, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-location-24.png"))); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(40, 24));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Odeljenja i odseci");

        javax.swing.GroupLayout jPanelOOLayout = new javax.swing.GroupLayout(jPanelOO);
        jPanelOO.setLayout(jPanelOOLayout);
        jPanelOOLayout.setHorizontalGroup(
            jPanelOOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOOLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        jPanelOOLayout.setVerticalGroup(
            jPanelOOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        jPanel1.add(jPanelOO);

        jPanelProizvodi.setBackground(new java.awt.Color(0, 153, 51));
        jPanelProizvodi.setPreferredSize(new java.awt.Dimension(200, 40));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-tree-30.png"))); // NOI18N
        jLabel32.setPreferredSize(new java.awt.Dimension(40, 30));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Proizvodi");

        javax.swing.GroupLayout jPanelProizvodiLayout = new javax.swing.GroupLayout(jPanelProizvodi);
        jPanelProizvodi.setLayout(jPanelProizvodiLayout);
        jPanelProizvodiLayout.setHorizontalGroup(
            jPanelProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProizvodiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel33)
                .addContainerGap())
        );
        jPanelProizvodiLayout.setVerticalGroup(
            jPanelProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProizvodiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProizvodiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        jPanel1.add(jPanelProizvodi);

        jPanelKupci.setBackground(new java.awt.Color(0, 153, 51));
        jPanelKupci.setPreferredSize(new java.awt.Dimension(200, 40));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-buyer-30.png"))); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(40, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Kupci");

        javax.swing.GroupLayout jPanelKupciLayout = new javax.swing.GroupLayout(jPanelKupci);
        jPanelKupci.setLayout(jPanelKupciLayout);
        jPanelKupciLayout.setHorizontalGroup(
            jPanelKupciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKupciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addContainerGap())
        );
        jPanelKupciLayout.setVerticalGroup(
            jPanelKupciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKupciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKupciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        jPanel1.add(jPanelKupci);

        jPanelOtpremaci.setBackground(new java.awt.Color(0, 153, 51));
        jPanelOtpremaci.setPreferredSize(new java.awt.Dimension(200, 40));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-worker-26.png"))); // NOI18N
        jLabel15.setPreferredSize(new java.awt.Dimension(40, 26));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Otpremači");

        javax.swing.GroupLayout jPanelOtpremaciLayout = new javax.swing.GroupLayout(jPanelOtpremaci);
        jPanelOtpremaci.setLayout(jPanelOtpremaciLayout);
        jPanelOtpremaciLayout.setHorizontalGroup(
            jPanelOtpremaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOtpremaciLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addContainerGap())
        );
        jPanelOtpremaciLayout.setVerticalGroup(
            jPanelOtpremaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOtpremaciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOtpremaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        jPanel1.add(jPanelOtpremaci);

        jPanelKorisnici.setBackground(new java.awt.Color(0, 153, 51));
        jPanelKorisnici.setPreferredSize(new java.awt.Dimension(200, 40));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-users-24 (1).png"))); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(40, 24));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Korisnici");

        javax.swing.GroupLayout jPanelKorisniciLayout = new javax.swing.GroupLayout(jPanelKorisnici);
        jPanelKorisnici.setLayout(jPanelKorisniciLayout);
        jPanelKorisniciLayout.setHorizontalGroup(
            jPanelKorisniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKorisniciLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addContainerGap())
        );
        jPanelKorisniciLayout.setVerticalGroup(
            jPanelKorisniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKorisniciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKorisniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        jPanel1.add(jPanelKorisnici);

        jPanelMojNalog.setBackground(new java.awt.Color(0, 153, 51));
        jPanelMojNalog.setPreferredSize(new java.awt.Dimension(200, 40));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-user-30.png"))); // NOI18N
        jLabel19.setPreferredSize(new java.awt.Dimension(40, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Moj nalog");

        javax.swing.GroupLayout jPanelMojNalogLayout = new javax.swing.GroupLayout(jPanelMojNalog);
        jPanelMojNalog.setLayout(jPanelMojNalogLayout);
        jPanelMojNalogLayout.setHorizontalGroup(
            jPanelMojNalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMojNalogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addContainerGap())
        );
        jPanelMojNalogLayout.setVerticalGroup(
            jPanelMojNalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMojNalogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMojNalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        jPanel1.add(jPanelMojNalog);

        jPanelOdjavise.setBackground(new java.awt.Color(0, 153, 51));
        jPanelOdjavise.setPreferredSize(new java.awt.Dimension(200, 40));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-exit-30.png"))); // NOI18N
        jLabel21.setPreferredSize(new java.awt.Dimension(40, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Odjavi se");

        javax.swing.GroupLayout jPanelOdjaviseLayout = new javax.swing.GroupLayout(jPanelOdjavise);
        jPanelOdjavise.setLayout(jPanelOdjaviseLayout);
        jPanelOdjaviseLayout.setHorizontalGroup(
            jPanelOdjaviseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOdjaviseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addContainerGap())
        );
        jPanelOdjaviseLayout.setVerticalGroup(
            jPanelOdjaviseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOdjaviseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOdjaviseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        jPanel1.add(jPanelOdjavise);

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));
        mainPanel.setPreferredSize(new java.awt.Dimension(1000, 700));
        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Dobrodošli nazad, izaberite opciju za pregled.");
        mainPanel.add(jLabel23, "card2");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAnaliza;
    private javax.swing.JPanel jPanelGJ;
    private javax.swing.JPanel jPanelKorisnici;
    private javax.swing.JPanel jPanelKupci;
    private javax.swing.JPanel jPanelLokaliteti;
    private javax.swing.JPanel jPanelMojNalog;
    private javax.swing.JPanel jPanelOO;
    private javax.swing.JPanel jPanelOdjavise;
    private javax.swing.JPanel jPanelOtpremaci;
    private javax.swing.JPanel jPanelOtpremnice;
    private javax.swing.JPanel jPanelProizvodi;
    private javax.swing.JPanel jPanelRacuni;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

    private void inicijalizacija() {

        addMouseListeners(jPanelAnaliza, "analiza");
        addMouseListeners(jPanelOtpremnice, "otpremnice");
        addMouseListeners(jPanelRacuni, "racuni");
        addMouseListeners(jPanelOO, "oo");
        addMouseListeners(jPanelGJ, "gj");
        addMouseListeners(jPanelLokaliteti, "lokaliteti");
        addMouseListeners(jPanelKupci, "kupci");
        addMouseListeners(jPanelOtpremaci, "otpremaci");
        addMouseListeners(jPanelKorisnici, "korisnici");
        addMouseListeners(jPanelOdjavise, "odjavise");
        addMouseListeners(jPanelMojNalog, "mojnalog");
        addMouseListeners(jPanelProizvodi, "proizvodi");

        cardProizvodi = new PanelProizvodi(this);
        cardKupci = new PanelKupci(this);
        cardLokaliteti = new PanelLokaliteti(this);
        cardOO = new PanelOO(this);
        cardGJ = new PanelGJ(this);
        cardKorisnici = new PanelKorisnici();
        cardMojNalog = new PanelMojNalog();
        cardOtpremnice = new PanelOtpremnice(this);
        cardAnaliza = new PanelAnaliza(this);
        cardRacuni = new PanelRacuni(this);
        cardOtpremaci = new PanelOtpremaci(this);

        mainPanel.add(cardProizvodi, "proizvodi");
        mainPanel.add(cardKupci, "kupci");
        mainPanel.add(cardLokaliteti, "lokaliteti");
        mainPanel.add(cardOO, "oo");
        mainPanel.add(cardGJ, "gj");
        mainPanel.add(cardKorisnici, "korisnici");
        mainPanel.add(cardMojNalog, "nalog");
        mainPanel.add(cardOtpremnice, "otpremnice");
        mainPanel.add(cardAnaliza, "analiza");
        mainPanel.add(cardRacuni, "racuni");
        mainPanel.add(cardOtpremaci, "otpremaci");

        cardLayout = (CardLayout) mainPanel.getLayout();

    }

    private void addMouseListeners(JPanel panel, String naziv) {
        // MouseListener za promenu boje na klik
        panel.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                // Ako je panel već selektovan, ništa se ne menja
                if (selectedPanel != panel) {
                    // Vratimo boju prethodnog selektovanog panela
                    if(panel == jPanelAnaliza && !"ADMINISTRATOR".equals(Controller.getInstance().getUlovovani().getPrivilegija().toString())){
                        return;
                    }
                    
                    if (selectedPanel != null) {
                        selectedPanel.setBackground(new Color(0, 153, 51));
                    }
                    // Selektujemo novi panel i menjamo mu boju
                    selectedPanel = panel;
                    panel.setBackground(new Color(0, 120, 51));
                }

                // Prikazivanje samo odgovarajuće kartice
                switch (naziv) {
                case "proizvodi" -> {
                    cardLayout.show(mainPanel, "proizvodi");
                    ((PanelProizvodi) cardProizvodi).azurirajTabelu();  // Resetujte panel kad se otvori
                    }
                case "analiza" -> {
                    if ("ADMINISTRATOR".equals(Controller.getInstance().getUlovovani().getPrivilegija().toString())) {
                        cardLayout.show(mainPanel, "analiza");
                        ((PanelAnaliza) cardAnaliza).azurirajTabelu();  // Resetujte panel kad se otvori
                    }
                    }
                case "otpremnice" -> {
                    cardLayout.show(mainPanel, "otpremnice");
                    ((PanelOtpremnice) cardOtpremnice).azurirajTabelu();  // Resetujte panel kad se otvori
                    }
                case "kupci" -> {
                    cardLayout.show(mainPanel, "kupci");
                    ((PanelKupci) cardKupci).azurirajTabelu();  // Resetujte panel kad se otvori
                    }
                case "oo" -> {
                    cardLayout.show(mainPanel, "oo");
                    ((PanelOO) cardOO).azurirajTabelu();  // Resetujte panel kad se otvori
                    }
                case "racuni" -> {
                    cardLayout.show(mainPanel, "racuni");
                    ((PanelRacuni) cardRacuni).azurirajTabelu();  // Resetujte panel kad se otvori
                    }
                case "lokaliteti" -> {
                    cardLayout.show(mainPanel, "lokaliteti");
                    ((PanelLokaliteti) cardLokaliteti).azurirajTabelu();  // Resetujte panel kad se otvori
                    }
                case "gj" -> {
                    cardLayout.show(mainPanel, "gj");
                    ((PanelGJ) cardGJ).azurirajTabelu();// Resetujte panel kad se otvori
                    }
                case "otpremaci" -> {
                    cardLayout.show(mainPanel, "otpremaci");
                    ((PanelOtpremaci) cardOtpremaci).azurirajTabelu();  // Resetujte panel kad se otvori
                    }
                case "korisnici" -> {
                    cardLayout.show(mainPanel, "korisnici");
                    ((PanelKorisnici) cardKorisnici).azurirajTabelu();  // Resetujte panel kad se otvori
                    }
                case "mojnalog" -> {
                    cardLayout.show(mainPanel, "nalog");
                    ((PanelMojNalog) cardMojNalog).azurirajTabelu();  // Resetujte panel kad se otvori
                    }
                case "odjavise" -> {
                    dispose();
                    new PrijavaForma().setVisible(true);
                    }
                default -> {
                    }
                }
            }

        }
        );

        // MouseMotionListener za promenu boje kada pređeš mišem preko panela
        panel.addMouseMotionListener(
                new MouseAdapter() {
            @Override
            public void mouseMoved(MouseEvent e
            ) {
                // Promenju boju na nijansu RGB(0, 153, 51) kada pređeš mišem
                if (selectedPanel != panel) {
                    panel.setBackground(new Color(0, 140, 51));  
                }
            }
        }
        );

        // Vratiti boju na početnu kada miš napusti panel
        panel.addMouseListener(
                new MouseAdapter() {
            @Override
            public void mouseExited(MouseEvent e
            ) {
                // Ako panel nije selektovan, vrati boju na početnu
                if (selectedPanel != panel) {
                    panel.setBackground(new Color(0, 153, 51));  // Početna boja
                }
            }
        }
        );

    }

    public void azurirajTabelu(String naziv) {
        switch (naziv) {
        case "otpremaci" -> cardOtpremaci.azurirajTabelu();
        case "kupci" -> cardKupci.azurirajTabelu();
        case "lokaliteti" -> cardLokaliteti.azurirajTabelu();
        case "gj" -> cardGJ.azurirajTabelu();
        case "oo" -> cardOO.azurirajTabelu();
        case "proizvodi" -> cardProizvodi.azurirajTabelu();
        case "otpremnice" -> cardOtpremnice.azurirajTabelu();
        default -> {
            }
        }
    }

}
