
package pogled;

import controller.Controller;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.GazdinskaJedinica;
import model.Lokalitet;
import model.OdeljenjeOdsek;
import model.Otpremnica;
import model.Proizvod;
import model.StavkaOtpremnice;
import model_enum.Klasa;
import model_enum.Tip;
import model_enum.Vrsta;
import table_models.StatistikaModelTabele;

import pogled.dialog.StatistikaDialog;

/**
 *
 * @author Andrej
 */
public class PanelAnaliza extends javax.swing.JPanel {

    private JFrame parent;

    /**
     * Creates new form PanelAnaliza
     */
    public PanelAnaliza(JFrame parent) {
        initComponents();
        this.parent = parent;
        inicijalizacija();
        popuniComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldGodina = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxKriterijum1 = new javax.swing.JComboBox<>();
        jComboBoxKriterijum2 = new javax.swing.JComboBox<>();
        jButtonAnaliza = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxOdeljenjeOdsek = new javax.swing.JComboBox<>();
        jComboBoxGazdinskaJedinica = new javax.swing.JComboBox<>();
        jComboBoxLokalitet = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTip = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxKlasa = new javax.swing.JComboBox<>();
        jComboBoxVrsta = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonLokalitet = new javax.swing.JRadioButton();
        jRadioButtonGJ = new javax.swing.JRadioButton();
        jRadioButtonOO = new javax.swing.JRadioButton();
        jRadioButtonReset = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDoznake = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 300));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 300));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 300));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Izaberite godinu ");
        jLabel8.setPreferredSize(new java.awt.Dimension(30, 16));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Izračunaj ");
        jLabel9.setPreferredSize(new java.awt.Dimension(30, 16));

        jComboBoxKriterijum1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROSEK", "UKUPNO", "UDEO" }));
        jComboBoxKriterijum1.setPreferredSize(new java.awt.Dimension(300, 30));

        jComboBoxKriterijum2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CENA", "KOLICINA" }));
        jComboBoxKriterijum2.setPreferredSize(new java.awt.Dimension(300, 30));

        jButtonAnaliza.setText("Analiziraj");
        jButtonAnaliza.setPreferredSize(new java.awt.Dimension(300, 40));
        jButtonAnaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnalizaActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Lokalitet");
        jLabel5.setPreferredSize(new java.awt.Dimension(30, 16));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Gazdinska jedinica");
        jLabel6.setPreferredSize(new java.awt.Dimension(30, 16));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Odeljenje i odsek");
        jLabel7.setPreferredSize(new java.awt.Dimension(30, 16));

        jComboBoxOdeljenjeOdsek.setPreferredSize(new java.awt.Dimension(300, 30));

        jComboBoxGazdinskaJedinica.setPreferredSize(new java.awt.Dimension(300, 30));

        jComboBoxLokalitet.setPreferredSize(new java.awt.Dimension(300, 30));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tip");
        jLabel2.setPreferredSize(new java.awt.Dimension(30, 16));

        jComboBoxTip.setPreferredSize(new java.awt.Dimension(300, 30));
        jComboBoxTip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Klasa");
        jLabel4.setPreferredSize(new java.awt.Dimension(30, 16));

        jComboBoxKlasa.setPreferredSize(new java.awt.Dimension(300, 30));

        jComboBoxVrsta.setPreferredSize(new java.awt.Dimension(300, 30));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Vrsta");
        jLabel3.setMinimumSize(new java.awt.Dimension(30, 16));

        jRadioButtonReset.setText("Sve");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxVrsta, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                            .addComponent(jComboBoxKlasa, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jComboBoxKriterijum1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(115, 115, 115))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxKriterijum2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTip, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxOdeljenjeOdsek, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxLokalitet, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxGazdinskaJedinica, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonOO)
                            .addComponent(jRadioButtonLokalitet)
                            .addComponent(jRadioButtonGJ)))
                    .addComponent(jButtonAnaliza, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonLokalitet, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxLokalitet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButtonGJ)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxGazdinskaJedinica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addComponent(jRadioButtonOO))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxVrsta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxOdeljenjeOdsek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonReset)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxKriterijum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxKriterijum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAnaliza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        jPanel2.setMinimumSize(new java.awt.Dimension(1000, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 400));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 350));
        jScrollPane1.setRequestFocusEnabled(false);

        jTableDoznake.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDoznake.setPreferredSize(new java.awt.Dimension(800, 350));
        jTableDoznake.setShowGrid(true);
        jScrollPane1.setViewportView(jTableDoznake);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnalizaActionPerformed
        Tip tip = (Tip) jComboBoxTip.getSelectedItem();
        Vrsta vrsta = (Vrsta) jComboBoxVrsta.getSelectedItem();
        Klasa klasa = (Klasa) jComboBoxKlasa.getSelectedItem();
        Lokalitet lokalitet = (Lokalitet) jComboBoxLokalitet.getSelectedItem();
        GazdinskaJedinica gazdinskaJedinica = (GazdinskaJedinica) jComboBoxGazdinskaJedinica.getSelectedItem();
        OdeljenjeOdsek odeljenjeOdsek = (OdeljenjeOdsek) jComboBoxOdeljenjeOdsek.getSelectedItem();
        if (!proveriComboBox()) {
            JOptionPane.showMessageDialog(parent, "Izaberite jedan kriterijum za mesto", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String godina = jTextFieldGodina.getText();
        String datumString;
        java.util.Date datum = null;
        if (!godina.isEmpty()) {
            datumString = godina + "-01-01";
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            try {
                datum = format.parse(datumString);
            } catch (ParseException ex) {
            }
        }

        String prosekUkupnoUdeo = (String) jComboBoxKriterijum1.getSelectedItem();
        String cenaKolicina = (String) jComboBoxKriterijum2.getSelectedItem();
        String radio = null;
        if(jRadioButtonLokalitet.isSelected()){
            radio = "LOKALITET";
        }else if(jRadioButtonGJ.isSelected()){
            radio = "GJ";
        }else if(jRadioButtonOO.isSelected()){
            radio = "OO";
        }

        Proizvod proizvod = new Proizvod();
        proizvod.setTip(tip);
        proizvod.setVrsta(vrsta);
        proizvod.setKlasa(klasa);

        Otpremnica otpremnica = new Otpremnica();
        otpremnica.setDatum(datum);

        StavkaOtpremnice so = new StavkaOtpremnice();
        
        OdeljenjeOdsek ooZaSlanje = odeljenjeOdsek;
        
        OdeljenjeOdsek oo2 = null;
        if (odeljenjeOdsek == null) {
            oo2 = new OdeljenjeOdsek();
        }
        GazdinskaJedinica gj2 = null;
        if (gazdinskaJedinica == null) {
             gj2 = new GazdinskaJedinica();
        }
        Lokalitet l2 = null;
        if(lokalitet == null){
            l2 = new Lokalitet();
        }
        so.setOtpremnica(otpremnica);
        so.setProizvod(proizvod);
//        gjZaSlanje.setLokalitet(lokalitet == null ? l2 : lokalitet);
//        ooZaSlanje.setGazdinskaJedinica(gazdinskaJedinica == null ? gj2 : gazdinskaJedinica);
        if(odeljenjeOdsek != null){
            ooZaSlanje = odeljenjeOdsek;
        }else if(gazdinskaJedinica != null){
            oo2.setGazdinskaJedinica(gazdinskaJedinica);
            ooZaSlanje = oo2;
        }else if(lokalitet != null){
            gj2.setLokalitet(lokalitet);
            oo2.setGazdinskaJedinica(gj2);
            ooZaSlanje = oo2;
        }else{
            ooZaSlanje = oo2;
        }
        
        so.setOdeljenjeOdsek(ooZaSlanje);

        List<Object[]> lista = new ArrayList<>();
        Controller.getInstance().analiziraj(so, prosekUkupnoUdeo, cenaKolicina, radio, lista);
        if (!lista.isEmpty()) {
            if (lista.get(0).length == 3) {

                List<Integer> vreme = new ArrayList<>();
                List<String> mesta = new ArrayList<>();
                List<Double> vrednosti = new ArrayList<>();

                for (int i = 0; i < lista.size(); i++) {
                    vreme.add((Integer) lista.get(i)[0]);
                    mesta.add((String) lista.get(i)[1]);
                    vrednosti.add((Double) lista.get(i)[2]);
                }
                boolean isGodina = jTextFieldGodina.getText().isEmpty();
                StatistikaDialog sd = new StatistikaDialog(parent, true, vreme, isGodina, mesta, vrednosti, cenaKolicina, prosekUkupnoUdeo);
                sd.setVisible(true);
            } else {
                ArrayList<Integer> vreme = new ArrayList<>();
                ArrayList<Double> vrednosti = new ArrayList<>();
                for (int i = 0; i < lista.size(); i++) {
                    vreme.add((Integer) lista.get(i)[0]);
                    vrednosti.add((Double) lista.get(i)[1]);
                }
                boolean isGodina = jTextFieldGodina.getText().isEmpty();
                StatistikaDialog sd = new StatistikaDialog(parent, true, vreme, isGodina, vrednosti, cenaKolicina, prosekUkupnoUdeo);
                sd.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nema rezultata za odabrane kriterijume", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAnalizaActionPerformed

    private void jComboBoxTipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnaliza;
    private javax.swing.JComboBox<GazdinskaJedinica> jComboBoxGazdinskaJedinica;
    private javax.swing.JComboBox<Klasa> jComboBoxKlasa;
    private javax.swing.JComboBox<String> jComboBoxKriterijum1;
    private javax.swing.JComboBox<String> jComboBoxKriterijum2;
    private javax.swing.JComboBox<Lokalitet> jComboBoxLokalitet;
    private javax.swing.JComboBox<OdeljenjeOdsek> jComboBoxOdeljenjeOdsek;
    private javax.swing.JComboBox<Tip> jComboBoxTip;
    private javax.swing.JComboBox<Vrsta> jComboBoxVrsta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonGJ;
    private javax.swing.JRadioButton jRadioButtonLokalitet;
    private javax.swing.JRadioButton jRadioButtonOO;
    private javax.swing.JRadioButton jRadioButtonReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDoznake;
    private javax.swing.JTextField jTextFieldGodina;
    // End of variables declaration//GEN-END:variables

    void azurirajTabelu() {
        inicijalizacija();
    }

    private boolean proveriComboBox() {
        int count = 0;
        if (jComboBoxLokalitet.getSelectedItem() != null) {
            count++;
        }
        if (jComboBoxGazdinskaJedinica.getSelectedItem() != null) {
            count++;
        }
        if (jComboBoxOdeljenjeOdsek.getSelectedItem() != null) {
            count++;
        }
        if (count == 0 || count == 1) {
            return true;
        }
        return false;
    }

    private void inicijalizacija() {
        
        ButtonGroup group = new ButtonGroup();
        group.add(jRadioButtonGJ);
        group.add(jRadioButtonLokalitet);
        group.add(jRadioButtonOO);
        group.add(jRadioButtonReset);
        jRadioButtonReset.setSelected(true);
        
        List<Object[]> podaci = new ArrayList<>();
        boolean uspesno = Controller.getInstance().vratiListuDoznakaOtprema(podaci);
        if (!uspesno) {
            JOptionPane.showMessageDialog(parent, "Greška prilikom učitavanja podataka", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        StatistikaModelTabele smt = new StatistikaModelTabele(podaci);
        jTableDoznake.setModel(smt);
//        HistogramExample.kreirajGrafikon(jPanelChart);
        //FunctionDiagram.kreirajDijagram(jPanelDiagram);

        //StackedDiagram.createStackedBarChart(jPanelStackedDiagram, lokaliteti, meseci, kolicine);    
    }

    private void popuniComboBox() {
        Tip[] tipovi = Tip.values();
        Vrsta[] vrste = Vrsta.values();
        Klasa[] klase = Klasa.values();

        List<Lokalitet> lokaliteti = new ArrayList<>();
        Controller.getInstance().vratiListuLokalitet(lokaliteti);

        List<GazdinskaJedinica> listaGJ = new ArrayList<>();
        Controller.getInstance().vratiListuGazdinskaJedinica(listaGJ);

        List<OdeljenjeOdsek> listaOO = new ArrayList<>();
        Controller.getInstance().vratiListuOdeljenjeOdsek(listaOO);

        // Dodavanje opcije "IZABERI" koja će predstavljati null vrednost
//        jComboBoxTip.removeAllItems();
        jComboBoxTip.addItem(null);
        for (Tip t : tipovi) {
            jComboBoxTip.addItem(t);
        }
        jComboBoxTip.setSelectedIndex(0); // Postavlja "IZABERI" kao podrazumevanu vrednost

//        jComboBoxVrsta.removeAllItems();
        jComboBoxVrsta.addItem(null);
        for (Vrsta v : vrste) {
            jComboBoxVrsta.addItem(v);
        }
        jComboBoxVrsta.setSelectedIndex(0);

//        jComboBoxKlasa.removeAllItems();
        jComboBoxKlasa.addItem(null);
        for (Klasa k : klase) {
            jComboBoxKlasa.addItem(k);
        }
        jComboBoxKlasa.setSelectedIndex(0);

//        jComboBoxOdeljenjeOdsek.removeAllItems();
        jComboBoxOdeljenjeOdsek.addItem(null);

        for (OdeljenjeOdsek oo : listaOO) {
            jComboBoxOdeljenjeOdsek.addItem(oo);
        }
        jComboBoxOdeljenjeOdsek.setSelectedIndex(0);

//        jComboBoxGazdinskaJedinica.removeAllItems();
        jComboBoxGazdinskaJedinica.addItem(null);
        for (GazdinskaJedinica gj : listaGJ) {
            jComboBoxGazdinskaJedinica.addItem(gj);
        }
        jComboBoxGazdinskaJedinica.setSelectedIndex(0);

//        jComboBoxLokalitet.removeAllItems();
        jComboBoxLokalitet.addItem(null);
        for (Lokalitet l : lokaliteti) {
            jComboBoxLokalitet.addItem(l);
        }
        jComboBoxLokalitet.setSelectedIndex(0);

    }

}
