/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pogled;

import controller.Controller;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Proizvod;
import model_enum.Klasa;
import model_enum.Tip;
import model_enum.Vrsta;
import pogled.dialog.ProizvodDialog;

import table_models.ProizvodModelTabele;

/**
 *
 * @author Andrej
 */
public class PanelProizvodi extends javax.swing.JPanel {

    JFrame parent;

    /**
     * Creates new form PanelProizvodi
     */
    public PanelProizvodi(JFrame parent) {
        initComponents();
        this.parent = parent;
        popuniComboBox();
        inicijalizacija();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel18 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableProizvodi = new javax.swing.JTable();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jComboBoxTip = new javax.swing.JComboBox<>();
        jPanel22 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jComboBoxVrsta = new javax.swing.JComboBox<>();
        jPanel23 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jComboBoxKlasa = new javax.swing.JComboBox<>();
        jPanel24 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jTextFieldCenaOd = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTextFieldCenaDo = new javax.swing.JTextField();
        jButtonFilter = new javax.swing.JButton();
        jButtonOcisti = new javax.swing.JButton();
        jButtonDetalji2 = new javax.swing.JButton();
        jButtonKreiraj2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new java.awt.BorderLayout());

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        jPanel18.setPreferredSize(new java.awt.Dimension(600, 700));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jScrollPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jTableProizvodi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProizvodi.setPreferredSize(new java.awt.Dimension(550, 650));
        jTableProizvodi.setShowGrid(true);
        jScrollPane4.setViewportView(jTableProizvodi);

        jPanel18.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        add(jPanel18, java.awt.BorderLayout.WEST);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        jPanel19.setPreferredSize(new java.awt.Dimension(400, 700));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setPreferredSize(new java.awt.Dimension(400, 400));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setPreferredSize(new java.awt.Dimension(350, 50));

        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Tip ");

        jComboBoxTip.setPreferredSize(new java.awt.Dimension(150, 26));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jComboBoxTip, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jComboBoxTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        jPanel20.add(jPanel21);

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setPreferredSize(new java.awt.Dimension(350, 50));

        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Vrsta ");

        jComboBoxVrsta.setPreferredSize(new java.awt.Dimension(150, 26));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jComboBoxVrsta, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jComboBoxVrsta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        jPanel20.add(jPanel22);

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setPreferredSize(new java.awt.Dimension(350, 50));

        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Klasa");

        jComboBoxKlasa.setPreferredSize(new java.awt.Dimension(150, 26));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jComboBoxKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jComboBoxKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        jPanel20.add(jPanel23);

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setPreferredSize(new java.awt.Dimension(350, 100));

        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Cena od");

        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("do");

        jButtonFilter.setText("Filter");
        jButtonFilter.setPreferredSize(new java.awt.Dimension(170, 27));
        jButtonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterActionPerformed(evt);
            }
        });

        jButtonOcisti.setText("Očisti");
        jButtonOcisti.setPreferredSize(new java.awt.Dimension(170, 27));
        jButtonOcisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOcistiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldCenaOd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel40)
                        .addGap(34, 34, 34)
                        .addComponent(jTextFieldCenaDo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOcisti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCenaOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(jTextFieldCenaDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOcisti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel20.add(jPanel24);

        jButtonDetalji2.setText("DETALJI");
        jButtonDetalji2.setPreferredSize(new java.awt.Dimension(400, 40));
        jButtonDetalji2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetalji2ActionPerformed(evt);
            }
        });

        jButtonKreiraj2.setText("KREIRAJ");
        jButtonKreiraj2.setPreferredSize(new java.awt.Dimension(400, 40));
        jButtonKreiraj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreiraj2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonKreiraj2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                        .addComponent(jButtonDetalji2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonDetalji2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonKreiraj2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel19, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterActionPerformed
        if (jComboBoxTip.getSelectedItem() == null && jComboBoxVrsta.getSelectedItem() == null && jComboBoxKlasa.getSelectedItem() == null && jTextFieldCenaOd.getText().isEmpty() && jTextFieldCenaDo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite kriterijum pretrage", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!jTextFieldCenaDo.getText().matches("^\\d$") || !jTextFieldCenaOd.getText().matches("^\\d*$")) {
            JOptionPane.showMessageDialog(this, "Unesite celobrojnu vrednost", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Tip tip = (Tip) jComboBoxTip.getSelectedItem();
        Vrsta vrsta = (Vrsta) jComboBoxVrsta.getSelectedItem();
        Klasa klasa = (Klasa) jComboBoxKlasa.getSelectedItem();
        double cenaOd = -1;
        double cenaDo = -1;
        Proizvod proizvod = new Proizvod();
        if (!jTextFieldCenaOd.getText().isEmpty()) {
            cenaOd = Double.parseDouble(jTextFieldCenaOd.getText());
        }
        if (!jTextFieldCenaDo.getText().isEmpty()) {
            cenaDo = Double.parseDouble(jTextFieldCenaDo.getText());
        }
        proizvod.setTip(tip);
        proizvod.setVrsta(vrsta);
        proizvod.setKlasa(klasa);
        proizvod.filterCena(cenaOd, cenaDo);
        List<Proizvod> lista = new ArrayList<>();
        boolean uspesno = Controller.getInstance().vratiListuSviProizvod(proizvod, lista);
        if (uspesno) {
            ProizvodModelTabele pmt = new ProizvodModelTabele(lista);
            jTableProizvodi.setModel(pmt);
        }
    }//GEN-LAST:event_jButtonFilterActionPerformed

    private void jButtonOcistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOcistiActionPerformed
        jComboBoxKlasa.setSelectedItem(null);
        jComboBoxTip.setSelectedItem(null);
        jComboBoxVrsta.setSelectedItem(null);
        jTextFieldCenaOd.setText("");
        jTextFieldCenaDo.setText("");
        inicijalizacija();
    }//GEN-LAST:event_jButtonOcistiActionPerformed

    private void jButtonDetalji2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetalji2ActionPerformed
        int red = jTableProizvodi.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Izaberite proizvod", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ProizvodModelTabele pmt = (ProizvodModelTabele) jTableProizvodi.getModel();
        Proizvod proizvod = pmt.getLista().get(red);
        ProizvodDialog pd = new ProizvodDialog(parent, true, proizvod);
        pd.setVisible(true);
    }//GEN-LAST:event_jButtonDetalji2ActionPerformed

    private void jButtonKreiraj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreiraj2ActionPerformed
        ProizvodDialog tdd = new ProizvodDialog(parent, true);
        tdd.setVisible(true);
    }//GEN-LAST:event_jButtonKreiraj2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetalji2;
    private javax.swing.JButton jButtonFilter;
    private javax.swing.JButton jButtonKreiraj2;
    private javax.swing.JButton jButtonOcisti;
    private javax.swing.JComboBox<Klasa> jComboBoxKlasa;
    private javax.swing.JComboBox<Tip> jComboBoxTip;
    private javax.swing.JComboBox<Vrsta> jComboBoxVrsta;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableProizvodi;
    private javax.swing.JTextField jTextFieldCenaDo;
    private javax.swing.JTextField jTextFieldCenaOd;
    // End of variables declaration//GEN-END:variables

    void azurirajTabelu() {
        inicijalizacija();
    }

    private void inicijalizacija() {
        List<Proizvod> lista = new ArrayList<>();
        boolean uspesno = Controller.getInstance().vratiListuProizvoda(lista);
        if (uspesno) {
            ProizvodModelTabele pmt = new ProizvodModelTabele(lista);
            jTableProizvodi.setModel(pmt);
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita listu proizvoda", "Greška", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void popuniComboBox() {
        for (Tip tip : Tip.values()) {
            jComboBoxTip.addItem(tip);
        }
        jComboBoxTip.setSelectedItem(null);
        for (Klasa klasa : Klasa.values()) {
            jComboBoxKlasa.addItem(klasa);
        }
        jComboBoxKlasa.setSelectedItem(null);
        for (Vrsta vrsta : Vrsta.values()) {
            jComboBoxVrsta.addItem(vrsta);
        }
        jComboBoxVrsta.setSelectedItem(null);
    }
}
