/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pogled;

import controller.Controller;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.GazdinskaJedinica;
import pogled.dialog.GazdinskaJedinicaDialog;
import table_models.GazdinskaJedinicaModelTabele;

/**
 *
 * @author Andrej
 */
public class PanelGJ extends javax.swing.JPanel {

    JFrame parent;
    /**
     * Creates new form PanelGJ
     */
    public PanelGJ(JFrame parent) {
        initComponents();
        this.parent = parent;
        inicijalizacija();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonDetalji = new javax.swing.JButton();
        jButtonKreiraj = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGJ = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(400, 700));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 100));

        jButtonDetalji.setText("DETALJI");
        jButtonDetalji.setPreferredSize(new java.awt.Dimension(350, 40));
        jButtonDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetaljiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDetalji);

        jButtonKreiraj.setText("KREIRAJ");
        jButtonKreiraj.setPreferredSize(new java.awt.Dimension(350, 40));
        jButtonKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonKreiraj);

        jPanel6.add(jPanel1, java.awt.BorderLayout.SOUTH);

        add(jPanel6, java.awt.BorderLayout.EAST);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        jPanel5.setPreferredSize(new java.awt.Dimension(600, 700));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(550, 650));

        jTableGJ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableGJ.setPreferredSize(new java.awt.Dimension(550, 650));
        jTableGJ.setShowGrid(true);
        jScrollPane1.setViewportView(jTableGJ);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajActionPerformed
        GazdinskaJedinicaDialog gjd = new GazdinskaJedinicaDialog(parent, true);
        gjd.setVisible(true);
    }//GEN-LAST:event_jButtonKreirajActionPerformed

    private void jButtonDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetaljiActionPerformed
        int red = jTableGJ.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Izaberite gazdinsku jedinicu", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        GazdinskaJedinicaModelTabele gjmt = (GazdinskaJedinicaModelTabele) jTableGJ.getModel();
        GazdinskaJedinica gj = gjmt.getLista().get(red);
        GazdinskaJedinicaDialog gjd = new GazdinskaJedinicaDialog(parent, true, gj);
        gjd.setVisible(true);
    }//GEN-LAST:event_jButtonDetaljiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetalji;
    private javax.swing.JButton jButtonKreiraj;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGJ;
    // End of variables declaration//GEN-END:variables

    void azurirajTabelu() {
        inicijalizacija();
    }

    private void inicijalizacija() {
        List<GazdinskaJedinica> lista = new ArrayList<>();
        boolean uspesno = Controller.getInstance().vratiListuGazdinskaJedinica(lista);
        if (uspesno) {
            GazdinskaJedinicaModelTabele gjmt = new GazdinskaJedinicaModelTabele(lista);
            jTableGJ.setModel(gjmt);
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita listu gazdinskih jedinica", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }


}
