/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pogled;

import controller.Controller;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Menadzer;
import tabela_model.MenadzerModelTabele;

/**
 *
 * @author Andrej
 */
public class PanelKorisnici extends javax.swing.JPanel {

    /**
     * Creates new form PanelKorisnici
     */
    public PanelKorisnici() {
        initComponents();
        inicijalizacija();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTableZaposleni = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new java.awt.BorderLayout());

        jScrollPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));

        jTableZaposleni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTableZaposleni);

        add(jScrollPane5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableZaposleni;
    // End of variables declaration//GEN-END:variables

    private void inicijalizacija() {
        List<Menadzer> lista = new ArrayList<>();
        boolean uspesno = Controller.getInstance().vratiListuZaposlenih(lista);
        if(uspesno){
            MenadzerModelTabele mmt = new MenadzerModelTabele(lista);
            jTableZaposleni.setModel(mmt);
        }else{
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita listu zaposlenih", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }

    void azurirajTabelu() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
