/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pogled;

import controller.Controller;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Kupac;
import model.Otpremac;
import model.Otpremnica;
import pogled.dialog.OtpremniceDialog;
import table_models.OtpremnicaModelTabele;

/**
 *
 * @author Andrej
 */
public class PanelOtpremnice extends javax.swing.JPanel {

    JFrame parent;
    /**
     * Creates new form PanelOtpremnice
     */
    public PanelOtpremnice(JFrame parent) {
        initComponents();
        inicijalizacija();
        popuniComboBox();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldBrojOtpremnice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldKupac = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxOtpremac = new javax.swing.JComboBox<>();
        jButtonFilter = new javax.swing.JButton();
        jButtonOcisti = new javax.swing.JButton();
        jButtonDetalji = new javax.swing.JButton();
        jButtonKreiraj = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOtpremnice = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 700));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 700));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Broj otpremnice");

        jTextFieldBrojOtpremnice.setPreferredSize(new java.awt.Dimension(150, 30));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Kupac");

        jTextFieldKupac.setPreferredSize(new java.awt.Dimension(150, 30));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Otpremač");

        jComboBoxOtpremac.setPreferredSize(new java.awt.Dimension(200, 30));

        jButtonFilter.setText("Filtriraj");
        jButtonFilter.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterActionPerformed(evt);
            }
        });

        jButtonOcisti.setText("Očisti");
        jButtonOcisti.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonOcisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOcistiActionPerformed(evt);
            }
        });

        jButtonDetalji.setText("Detalji");
        jButtonDetalji.setPreferredSize(new java.awt.Dimension(300, 40));
        jButtonDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetaljiActionPerformed(evt);
            }
        });

        jButtonKreiraj.setText("Kreiraj");
        jButtonKreiraj.setPreferredSize(new java.awt.Dimension(300, 40));
        jButtonKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonKreiraj, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(jButtonDetalji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonOcisti, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldKupac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldBrojOtpremnice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxOtpremac, 0, 210, Short.MAX_VALUE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldBrojOtpremnice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxOtpremac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButtonFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOcisti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                .addComponent(jButtonDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonKreiraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 700));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 700));

        jTableOtpremnice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTableOtpremnice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableOtpremnice.setPreferredSize(new java.awt.Dimension(600, 600));
        jTableOtpremnice.setShowGrid(true);
        jScrollPane1.setViewportView(jTableOtpremnice);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterActionPerformed
        
        if(jTextFieldBrojOtpremnice.getText().isEmpty()
                && jTextFieldKupac.getText().isEmpty()
                &&jComboBoxOtpremac.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "Izaberite kriterijum pretrage","Upozorenje",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!jTextFieldBrojOtpremnice.getText().matches("^\\d*$")){
            JOptionPane.showMessageDialog(this, "Pogrešni parametri pretrage","Upozorenje",JOptionPane.ERROR_MESSAGE);
            return;
        }
        String brojOtpremnice = "";
        if (!jTextFieldBrojOtpremnice.getText().isEmpty()) {
            brojOtpremnice = jTextFieldBrojOtpremnice.getText();
        }
        String nazivKupca = jTextFieldKupac.getText();
        Kupac kupac = new Kupac();
        kupac.setNaziv(nazivKupca);
        Otpremac otpremac = (Otpremac) jComboBoxOtpremac.getSelectedItem();
        Otpremnica otpremnica = new Otpremnica();
        otpremnica.setBroj(brojOtpremnice);
        otpremnica.setKupac(kupac);
        otpremnica.setOtpremac(otpremac);
        List<Otpremnica> lista = new ArrayList<>();

        boolean uspesno = Controller.getInstance().vratiListuSviOtpremnica(otpremnica, lista);
        if (uspesno) {
            OtpremnicaModelTabele omt = new OtpremnicaModelTabele(lista);
            jTableOtpremnice.setModel(omt);
        }
    }//GEN-LAST:event_jButtonFilterActionPerformed

    private void jButtonOcistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOcistiActionPerformed
        jTextFieldBrojOtpremnice.setText("");
        jTextFieldKupac.setText("");
        jComboBoxOtpremac.setSelectedItem(null);
        inicijalizacija();
    }//GEN-LAST:event_jButtonOcistiActionPerformed

    private void jButtonKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajActionPerformed
        OtpremniceDialog od = new OtpremniceDialog(parent, true);
        od.setVisible(true);
    }//GEN-LAST:event_jButtonKreirajActionPerformed

    private void jButtonDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetaljiActionPerformed
        int red = jTableOtpremnice.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Odaberite otpremnicu", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        OtpremnicaModelTabele omt = (OtpremnicaModelTabele) jTableOtpremnice.getModel();
        Otpremnica otpremnica = omt.getLista().get(red);
        
        OtpremniceDialog od = new OtpremniceDialog(parent, true, otpremnica);
        od.setVisible(true);
    }//GEN-LAST:event_jButtonDetaljiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetalji;
    private javax.swing.JButton jButtonFilter;
    private javax.swing.JButton jButtonKreiraj;
    private javax.swing.JButton jButtonOcisti;
    private javax.swing.JComboBox<Otpremac> jComboBoxOtpremac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOtpremnice;
    private javax.swing.JTextField jTextFieldBrojOtpremnice;
    private javax.swing.JTextField jTextFieldKupac;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBox() {
        List<Otpremac> otpremaci = new ArrayList<>();
        Controller.getInstance().vratiListuOtpremaca(otpremaci);
        for (Otpremac o : otpremaci) {
            jComboBoxOtpremac.addItem(o);
        }
        jComboBoxOtpremac.setSelectedItem(null);
    }

    private void inicijalizacija() {
        List<Otpremnica> lista = new ArrayList<>();
        boolean uspesno = Controller.getInstance().vratiListuOtpremnica(lista);
        if (uspesno) {
            OtpremnicaModelTabele omt = new OtpremnicaModelTabele(lista);
            jTableOtpremnice.setModel(omt);
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita listu otpremnica", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }

    void azurirajTabelu() {
        inicijalizacija();
    }
}
