/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pogled;

import controller.Controller;
import email.Email;
import hashing.Hash;
import java.awt.Color;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.security.NoSuchAlgorithmException;
import java.util.Random;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import model.Menadzer;
import model.MenadzerPrivilegija;
import model_enum.Privilegija;
import view.RegistracijaForma;

/**
 *
 * @author Andrej
 */
public class PrijavaForma extends javax.swing.JFrame {

    /**
     * Creates new form PrijavaForma
     */
    public PrijavaForma() {
        initComponents();
        setTitle("Prijava");
        setResizable(false);
        setLocationRelativeTo(null);
        popuniComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLevo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanelDesno = new javax.swing.JPanel();
        jPanelPrijava = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldJmbgPrijava = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        jButtonPrijava = new javax.swing.JButton();
        jPanelRegistracija = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldJMBG = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldImePrezime = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPasswordFieldRegistracija = new javax.swing.JPasswordField();
        jPanel17 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldKontakt = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jComboBoxPrivilegija = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        jButtonRegistracija = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanelLevo.setBackground(new java.awt.Color(0, 153, 51));
        jPanelLevo.setMaximumSize(new java.awt.Dimension(200, 400));
        jPanelLevo.setMinimumSize(new java.awt.Dimension(200, 400));
        jPanelLevo.setPreferredSize(new java.awt.Dimension(200, 400));

        jPanel2.setBackground(new java.awt.Color(0, 153, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 100));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dobrodošli nazad");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanelLevo.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 153, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 100));

        jButton1.setBackground(new java.awt.Color(0, 102, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PRIJAVA");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton1.setPreferredSize(new java.awt.Dimension(150, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setBackground(new java.awt.Color(0, 153, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REGISTRACIJA");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton2.setPreferredSize(new java.awt.Dimension(150, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jPanelLevo.add(jPanel3);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-tree-96.png"))); // NOI18N
        jPanelLevo.add(jLabel9);

        getContentPane().add(jPanelLevo);

        jPanelDesno.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDesno.setMaximumSize(new java.awt.Dimension(400, 400));
        jPanelDesno.setMinimumSize(new java.awt.Dimension(400, 400));
        jPanelDesno.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanelDesno.setLayout(new java.awt.CardLayout());

        jPanelPrijava.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPrijava.setMaximumSize(new java.awt.Dimension(300, 200));
        jPanelPrijava.setMinimumSize(new java.awt.Dimension(300, 200));
        jPanelPrijava.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanelPrijava.setLayout(new java.awt.GridBagLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setMaximumSize(new java.awt.Dimension(300, 200));
        jPanel9.setMinimumSize(new java.awt.Dimension(300, 200));
        jPanel9.setPreferredSize(new java.awt.Dimension(300, 200));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMinimumSize(new java.awt.Dimension(300, 100));
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 60));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("JMBG");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel6.add(jLabel2);

        jTextFieldJmbgPrijava.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldJmbgPrijava.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldJmbgPrijava.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldJmbgPrijava.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldJmbgPrijava.setText("0202003773622");
        jTextFieldJmbgPrijava.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldJmbgPrijava.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel6.add(jTextFieldJmbgPrijava);

        jPanel9.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setMinimumSize(new java.awt.Dimension(300, 50));
        jPanel7.setPreferredSize(new java.awt.Dimension(300, 60));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Lozinka");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel7.add(jLabel3);

        jPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField.setText("emperijeri");
        jPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPasswordField.setPreferredSize(new java.awt.Dimension(200, 30));
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        jPanel7.add(jPasswordField);

        jPanel9.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setMinimumSize(new java.awt.Dimension(300, 50));
        jPanel8.setPreferredSize(new java.awt.Dimension(300, 60));

        jButtonPrijava.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPrijava.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPrijava.setText("Prijavi se");
        jButtonPrijava.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonPrijava.setPreferredSize(new java.awt.Dimension(200, 30));
        jButtonPrijava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrijavaActionPerformed(evt);
            }
        });
        jPanel8.add(jButtonPrijava);

        jPanel9.add(jPanel8);

        jPanelPrijava.add(jPanel9, new java.awt.GridBagConstraints());

        jPanelDesno.add(jPanelPrijava, "card2");

        jPanelRegistracija.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRegistracija.setMaximumSize(new java.awt.Dimension(300, 200));
        jPanelRegistracija.setPreferredSize(new java.awt.Dimension(300, 400));
        jPanelRegistracija.setLayout(new java.awt.GridBagLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setMaximumSize(new java.awt.Dimension(300, 200));
        jPanel11.setMinimumSize(new java.awt.Dimension(300, 200));
        jPanel11.setPreferredSize(new java.awt.Dimension(300, 400));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setMinimumSize(new java.awt.Dimension(300, 100));
        jPanel12.setPreferredSize(new java.awt.Dimension(300, 50));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("JMBG");
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel12.add(jLabel4);

        jTextFieldJMBG.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldJMBG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldJMBG.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldJMBG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldJMBG.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel12.add(jTextFieldJMBG);

        jPanel11.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setMinimumSize(new java.awt.Dimension(300, 50));
        jPanel13.setPreferredSize(new java.awt.Dimension(300, 50));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ime i prezime");
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel13.add(jLabel5);

        jTextFieldImePrezime.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldImePrezime.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldImePrezime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldImePrezime.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel13.add(jTextFieldImePrezime);

        jPanel11.add(jPanel13);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setMinimumSize(new java.awt.Dimension(300, 50));
        jPanel15.setPreferredSize(new java.awt.Dimension(300, 50));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Email");
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel15.add(jLabel6);

        jTextFieldEmail.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmail.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldEmail.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel15.add(jTextFieldEmail);

        jPanel11.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setMinimumSize(new java.awt.Dimension(300, 50));
        jPanel16.setPreferredSize(new java.awt.Dimension(300, 50));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Lozinka");
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel16.add(jLabel7);

        jPasswordFieldRegistracija.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel16.add(jPasswordFieldRegistracija);

        jPanel11.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setMinimumSize(new java.awt.Dimension(300, 50));
        jPanel17.setPreferredSize(new java.awt.Dimension(300, 50));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Kontakt");
        jLabel8.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel17.add(jLabel8);

        jTextFieldKontakt.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldKontakt.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldKontakt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldKontakt.setPreferredSize(new java.awt.Dimension(200, 20));
        jPanel17.add(jTextFieldKontakt);

        jPanel11.add(jPanel17);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setMinimumSize(new java.awt.Dimension(300, 50));
        jPanel18.setPreferredSize(new java.awt.Dimension(300, 50));

        jComboBoxPrivilegija.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxPrivilegija.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBoxPrivilegija.setPreferredSize(new java.awt.Dimension(200, 25));
        jPanel18.add(jComboBoxPrivilegija);

        jPanel11.add(jPanel18);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setMinimumSize(new java.awt.Dimension(300, 50));
        jPanel14.setPreferredSize(new java.awt.Dimension(300, 60));

        jButtonRegistracija.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegistracija.setForeground(new java.awt.Color(0, 0, 0));
        jButtonRegistracija.setText("Registruj se");
        jButtonRegistracija.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonRegistracija.setPreferredSize(new java.awt.Dimension(200, 30));
        jButtonRegistracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistracijaActionPerformed(evt);
            }
        });
        jPanel14.add(jButtonRegistracija);

        jPanel11.add(jPanel14);

        jPanelRegistracija.add(jPanel11, new java.awt.GridBagConstraints());

        jPanelDesno.add(jPanelRegistracija, "card2");

        getContentPane().add(jPanelDesno);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jPanelRegistracija.setVisible(true);
        jPanelPrijava.setVisible(false);
        jButton1.setBackground(new Color(0, 153, 51));
        jButton2.setBackground(new Color(0, 102, 51));

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanelRegistracija.setVisible(false);
        jPanelPrijava.setVisible(true);
        jButton1.setBackground(new Color(0, 102, 51));
        jButton2.setBackground(new Color(0, 153, 51));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonPrijavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrijavaActionPerformed
        
        String jmbg = jTextFieldJmbgPrijava.getText().trim();
        String lozinka = new String(jPasswordField.getPassword());
        String kriptovana = "";
        try {
            kriptovana = Hash.kriptuj(lozinka);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(PrijavaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
        boolean uspesno = Controller.getInstance().prijaviMenadzer(jmbg, kriptovana);
        if (uspesno) {
            GlavnaForma gf = new GlavnaForma();
            gf.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Pogrešni kredencijali", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPrijavaActionPerformed

    private void jButtonRegistracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistracijaActionPerformed
        if (jTextFieldJMBG.getText().isEmpty() 
                || !jTextFieldJMBG.getText().matches("^\\d{13}$")
                || jTextFieldImePrezime.getText().isEmpty() 
                || jTextFieldEmail.getText().isEmpty()
                || !jTextFieldEmail.getText().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")
                || jTextFieldKontakt.getText().isEmpty()
                || jPasswordFieldRegistracija.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Proverite format unetih podataka","Greška",JOptionPane.ERROR_MESSAGE);
            return;
        }
        String jmbg = jTextFieldJMBG.getText();
        String imePrezime = jTextFieldImePrezime.getText();
        String email = jTextFieldEmail.getText();
        String kontakt = jTextFieldKontakt.getText();
        Privilegija privilegija = (Privilegija)jComboBoxPrivilegija.getSelectedItem();
        String lozinka = String.valueOf(jPasswordFieldRegistracija.getPassword());
        String kriptovana = "";
        try {
            kriptovana = Hash.kriptuj(lozinka);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(PrijavaForma.class.getName()).log(Level.SEVERE, null, ex);
        }

        Menadzer menadzer = new Menadzer(jmbg, imePrezime, email,kriptovana, kontakt,privilegija );
        boolean uspesno = Controller.getInstance().kreirajMenadzer(menadzer);
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Dobili ste jednokratnu lozinku na mail "+email, "Uspešno", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Greška prilikom registracije na sistem", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRegistracijaActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrijavaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrijavaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrijavaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrijavaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrijavaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonPrijava;
    private javax.swing.JButton jButtonRegistracija;
    private javax.swing.JComboBox<Privilegija> jComboBoxPrivilegija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelDesno;
    private javax.swing.JPanel jPanelLevo;
    private javax.swing.JPanel jPanelPrijava;
    private javax.swing.JPanel jPanelRegistracija;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordFieldRegistracija;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldImePrezime;
    private javax.swing.JTextField jTextFieldJMBG;
    private javax.swing.JTextField jTextFieldJmbgPrijava;
    private javax.swing.JTextField jTextFieldKontakt;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBox() {
        for (Privilegija p : Privilegija.values()) {
            jComboBoxPrivilegija.addItem(p);
        }
    }
}
