/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pogled.dialog;

import controller.Controller;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.GazdinskaJedinica;
import model.OdeljenjeOdsek;
import pogled.GlavnaForma;

/**
 *
 * @author Andrej
 */
public class OdeljenjeOdsekDialog extends javax.swing.JDialog {

    private OdeljenjeOdsek oo;
    private GlavnaForma parent;
    private double staraDoznaka;

    public OdeljenjeOdsekDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("Kreiraj odeljenje i odsek");
        inicijalizacija();
        popuniComboBox();
        this.parent = (GlavnaForma) parent;
    }

    public OdeljenjeOdsekDialog(java.awt.Frame parent, boolean modal, OdeljenjeOdsek oo) {
        super(parent, modal);
        this.oo = oo;
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("Detalji mesta");
        inicijalizacija(oo);
        popuniComboBox();
        this.parent = (GlavnaForma) parent;
        this.staraDoznaka = oo.getDoznaka();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDoznaka = new javax.swing.JTextField();
        jComboBoxJG = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDatumDoznake = new javax.swing.JTextField();
        jLabelNazivError = new javax.swing.JLabel();
        jLabelDoznakaError = new javax.swing.JLabel();
        jLabelDatumDoznakeError = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonSacuvajIzmene = new javax.swing.JButton();
        jButtonIzmeni = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jButtonKreiraj = new javax.swing.JButton();

        jButton3.setText("Izmeni");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Naziv");

        jTextFieldNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNazivActionPerformed(evt);
            }
        });

        jLabel2.setText("Gazdinska jedinica");

        jLabel3.setText("Doznaka");

        jComboBoxJG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJGActionPerformed(evt);
            }
        });

        jLabel4.setText("Datum doznake");

        jTextFieldDatumDoznake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDatumDoznakeActionPerformed(evt);
            }
        });

        jLabelNazivError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelNazivError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelNazivError.setText("jLabel5");

        jLabelDoznakaError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelDoznakaError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelDoznakaError.setText("jLabel5");

        jLabelDatumDoznakeError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelDatumDoznakeError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelDatumDoznakeError.setText("jLabel5");

        jLabel6.setText("m3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(203, 203, 203))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldNaziv)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNazivError, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxJG, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldDoznaka, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelDoznakaError, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 6, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDatumDoznakeError, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDatumDoznake, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxJG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNazivError)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDoznaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(5, 5, 5)))
                .addComponent(jLabelDoznakaError)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDatumDoznake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDatumDoznakeError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonSacuvajIzmene.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonSacuvajIzmene.setText("Sačuvaj izmene");
        jButtonSacuvajIzmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajIzmeneActionPerformed(evt);
            }
        });

        jButtonIzmeni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonIzmeni.setText("Izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        jButtonObrisi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonObrisi.setText("Obriši");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jButtonKreiraj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonKreiraj.setText("Kreiraj");
        jButtonKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonIzmeni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSacuvajIzmene, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(jButtonKreiraj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonObrisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButtonIzmeni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSacuvajIzmene)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonKreiraj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonObrisi)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
        jTextFieldNaziv.setEnabled(true);
        jTextFieldDatumDoznake.setEnabled(false);
        jTextFieldDoznaka.setEnabled(true);
        jComboBoxJG.setEnabled(true);
        jButtonIzmeni.setEnabled(false);
        jButtonSacuvajIzmene.setEnabled(true);
    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    private void jComboBoxJGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJGActionPerformed

    private void jTextFieldNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNazivActionPerformed

    private void jButtonSacuvajIzmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajIzmeneActionPerformed
        if (jTextFieldDoznaka.getText().isEmpty()
                || !jTextFieldDoznaka.getText().matches("\\d+(\\.\\d+)?")
                || jTextFieldDatumDoznake.getText().isEmpty()) {
            jLabelNazivError.setText(jTextFieldNaziv.getText().isEmpty() ? "Unesite odsek i odeljenje" : "");
            jLabelDoznakaError.setText(jTextFieldDoznaka.getText().isEmpty() ? "Unesite doznaku"
                    : !jTextFieldDoznaka.getText().matches("\\d+(\\.\\d+)?") ? "Unesite broj" : "");
            return;
        }
        GazdinskaJedinica gj = (GazdinskaJedinica) jComboBoxJG.getSelectedItem();
        String naziv = jTextFieldNaziv.getText();
        double novaDoznaka = Double.parseDouble(this.jTextFieldDoznaka.getText());
        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy.");
        java.util.Date datum = null;

        try {
            datum = format.parse(this.jTextFieldDatumDoznake.getText());
        } catch (ParseException ex) {
            Logger.getLogger(OdeljenjeOdsekDialog.class.getName()).log(Level.SEVERE, null, ex);
        }

        oo.setNaziv(naziv);
        oo.setGazdinskaJedinica(gj);
        oo.setDoznaka(novaDoznaka);
        oo.setDatumDoznake(datum);

        boolean uspesno = Controller.getInstance().izmeniOdeljenjeOdsek(oo);
//        if (staraDoznaka != novaDoznaka) {
//            try {
//                Email.promeniDoznaku(staraDoznaka, novaDoznaka, Controller.getInstance().getUlovovani(), oo);
//            } catch (MessagingException ex) {
//                Logger.getLogger(OdeljenjeOdsekDialog.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
        if (!uspesno) {
            JOptionPane.showMessageDialog(this, "Greška prilikom izmene odeljenja i odseka", "Greška", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Uspešno izmenjeno mesto", "Uspešno", JOptionPane.INFORMATION_MESSAGE);
            parent.azurirajTabelu("oo");
            this.dispose();
        }

    }//GEN-LAST:event_jButtonSacuvajIzmeneActionPerformed

    private void jButtonKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajActionPerformed
        this.setValidationLabels();
        if (jTextFieldDoznaka.getText().isEmpty()
                || !jTextFieldDoznaka.getText().matches("\\d+(\\.\\d+)?")
                || jTextFieldDatumDoznake.getText().isEmpty()) {
            jLabelNazivError.setText(jTextFieldNaziv.getText().isEmpty() ? "Unesite odsek i odeljenje" : "");
            jLabelDoznakaError.setText(jTextFieldDoznaka.getText().isEmpty() ? "Unesite doznaku"
                    : !jTextFieldDoznaka.getText().matches("\\d+(\\.\\d+)?") ? "Unesite broj" : "");
            return;
        }

        GazdinskaJedinica gj = (GazdinskaJedinica) jComboBoxJG.getSelectedItem();
        String naziv = jTextFieldNaziv.getText();
        double novaDoznaka = Double.parseDouble(this.jTextFieldDoznaka.getText());
        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy.");
        java.util.Date datum = null;

        try {
            datum = format.parse(this.jTextFieldDatumDoznake.getText());
        } catch (ParseException ex) {
            Logger.getLogger(OdeljenjeOdsekDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        oo = new OdeljenjeOdsek();
        oo.setNaziv(naziv);
        oo.setGazdinskaJedinica(gj);
        oo.setDoznaka(novaDoznaka);
        oo.setDatumDoznake(datum);
        boolean uspesno = Controller.getInstance().kreirajOdeljenjeOdsek(oo);
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Odeljenje i odsek uspešno kreirani", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
            parent.azurirajTabelu("oo");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Greška prilikom kreiranja odeljenja i odseka", "Greška", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonKreirajActionPerformed

    private void jTextFieldDatumDoznakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDatumDoznakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDatumDoznakeActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        int odgovor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da obrišete odeljenje i odsek?", "Potvrda", JOptionPane.YES_NO_OPTION);
        if (odgovor == JOptionPane.YES_OPTION) {
            boolean uspesno = Controller.getInstance().obrisiOdeljenjeOdsek(oo);
            if (!uspesno) {
                JOptionPane.showMessageDialog(this, "Greška prilikom brisanja odeljenja i odseka", "Greška", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Uspešno obrisano odeljenjei odsek", "Uspešno", JOptionPane.INFORMATION_MESSAGE);
                parent.azurirajTabelu("oo");
                this.dispose();
            }
        }
        return;
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonKreiraj;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonSacuvajIzmene;
    private javax.swing.JComboBox<GazdinskaJedinica> jComboBoxJG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDatumDoznakeError;
    private javax.swing.JLabel jLabelDoznakaError;
    private javax.swing.JLabel jLabelNazivError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldDatumDoznake;
    private javax.swing.JTextField jTextFieldDoznaka;
    private javax.swing.JTextField jTextFieldNaziv;
    // End of variables declaration//GEN-END:variables

    private void inicijalizacija() {
        jComboBoxJG.setSelectedItem(null);
        jButtonSacuvajIzmene.setVisible(false);
        jButtonIzmeni.setVisible(false);
        jButtonObrisi.setVisible(false);
        java.util.Date datum = new java.util.Date();
        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy.");
        String datumString = format.format(datum);
        jTextFieldDatumDoznake.setText(datumString);
        jTextFieldDatumDoznake.setEnabled(false);

        this.setValidationLabels();

    }

    private void inicijalizacija(OdeljenjeOdsek oo) {

        jComboBoxJG.setSelectedItem(oo.getGazdinskaJedinica());
        jComboBoxJG.setEnabled(false);
        jButtonKreiraj.setVisible(false);
        jButtonSacuvajIzmene.setEnabled(false);
        jTextFieldNaziv.setText(oo.getNaziv());
        jTextFieldDoznaka.setText(oo.getDoznaka() + "");
        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy.");
        try {
            jTextFieldDatumDoznake.setText(format.format(oo.getDatumDoznake()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pogresan format datuma", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        jTextFieldNaziv.setEnabled(false);
        jTextFieldDatumDoznake.setEnabled(false);
        jTextFieldDoznaka.setEnabled(false);
        jComboBoxJG.setEnabled(false);

        this.setValidationLabels();

    }

    private void setValidationLabels() {
        jLabelNazivError.setText("");
        jLabelDoznakaError.setText("");
        jLabelDatumDoznakeError.setText("");
    }

    private void popuniComboBox() {

        List<GazdinskaJedinica> listaGJ = new ArrayList<>();
        boolean uspesno2 = Controller.getInstance().vratiListuGazdinskaJedinica(listaGJ);
        if (uspesno2) {
            for (GazdinskaJedinica gj : listaGJ) {
                jComboBoxJG.addItem(gj);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita listu gazdinskih jedinica", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }
}
