package pogled.dialog;

import controller.Controller;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.GazdinskaJedinica;
import model.Kupac;
import model.Menadzer;
import model.OdeljenjeOdsek;
import model.Otpremac;
import model.Otpremnica;
import model.Proizvod;
import model.StavkaOtpremnice;
import model_enum.Klasa;
import model_enum.Tip;
import model_enum.Vrsta;
import pogled.GlavnaForma;
import table_models.StavkaOtpremniceModelTabele;

/**
 *
 * @author Andrej
 */
public class OtpremniceDialog extends javax.swing.JDialog {

    private GlavnaForma parent = new GlavnaForma();
    private double sumiranaCena = 0;
    Otpremnica otpremnica;

    public OtpremniceDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        popuniComboBox();
        inicijalizacija();
        setLocationRelativeTo(parent);
        setResizable(false);
        this.parent = (GlavnaForma) parent;
        setTitle("Otpremnica");
    }

    public OtpremniceDialog(java.awt.Frame parent, boolean modal, Otpremnica otpremnica) {
        super(parent, modal);
        initComponents();
        this.otpremnica = otpremnica;
        popuniComboBox();
        inicijalizacija(otpremnica);
        setLocationRelativeTo(parent);
        setResizable(false);
        this.parent = (GlavnaForma) parent;
        setTitle("Otpremnica");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldBrojOtpremnice = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jComboBoxMenadzer = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jComboBoxGJ = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jComboBoxOtpremac = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jComboBoxFirma = new javax.swing.JComboBox<>();
        jTextFieldKupac = new javax.swing.JTextField();
        jButtonOcisti = new javax.swing.JButton();
        jButtonPronadjiKupac = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDatumOtpremnice = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTip = new javax.swing.JComboBox<>();
        jComboBoxVrsta = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxKlasa = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButtonPronadjiProizvod = new javax.swing.JButton();
        jComboBoxProizvodi = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButtonDodajProizvod = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCena = new javax.swing.JTextField();
        jLabelProizvodError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldKolicina = new javax.swing.JTextField();
        jTextFieldMernaJedinica = new javax.swing.JTextField();
        jLabelKolicinaError = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldRabat = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxOO = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxPDV = new javax.swing.JComboBox<>();
        jButtonObrisi1 = new javax.swing.JButton();
        jLabelRabatError = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldUkupnaCena = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButtonKreirajOtpremnicu = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStavkeOtpremnice = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 750));

        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 400));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(350, 400));
        jPanel1.add(jLabel3);

        jPanel5.setPreferredSize(new java.awt.Dimension(350, 50));

        jLabel6.setText("Broj otpremnice");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel6)
                .addGap(45, 45, 45)
                .addComponent(jTextFieldBrojOtpremnice, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldBrojOtpremnice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel5);

        jPanel6.setPreferredSize(new java.awt.Dimension(350, 50));

        jLabel23.setText("Menadzer");

        jComboBoxMenadzer.setPreferredSize(new java.awt.Dimension(100, 26));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jComboBoxMenadzer, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jComboBoxMenadzer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(350, 50));

        jLabel24.setText("Gazdinska jedinica");

        jComboBoxGJ.setPreferredSize(new java.awt.Dimension(100, 26));
        jComboBoxGJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jComboBoxGJ, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jComboBoxGJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel7);

        jPanel8.setPreferredSize(new java.awt.Dimension(350, 50));

        jLabel25.setText("Otpremač");

        jComboBoxOtpremac.setPreferredSize(new java.awt.Dimension(100, 26));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jComboBoxOtpremac, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jComboBoxOtpremac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
        );

        jPanel1.add(jPanel8);

        jPanel10.setPreferredSize(new java.awt.Dimension(350, 100));

        jLabel27.setText("Kupac");

        jButtonOcisti.setText("Očisti");
        jButtonOcisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOcistiActionPerformed(evt);
            }
        });

        jButtonPronadjiKupac.setText("Filtriraj");
        jButtonPronadjiKupac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPronadjiKupacActionPerformed(evt);
            }
        });

        jLabel28.setText("Naziv");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addGap(33, 33, 33)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxFirma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jTextFieldKupac, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jButtonPronadjiKupac)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOcisti)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOcisti)
                    .addComponent(jButtonPronadjiKupac)
                    .addComponent(jLabel28))
                .addGap(6, 6, 6)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxFirma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(77, 77, 77))
        );

        jPanel1.add(jPanel10);

        jPanel11.setPreferredSize(new java.awt.Dimension(350, 50));

        jLabel7.setText("Datum otpremnice");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jTextFieldDatumOtpremnice, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldDatumOtpremnice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel11);

        jPanel3.add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel12.setPreferredSize(new java.awt.Dimension(650, 400));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Tip");

        jLabel4.setText("Vrsta");

        jLabel5.setText("Klasa");

        jButtonPronadjiProizvod.setText("Pronadji");
        jButtonPronadjiProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPronadjiProizvodActionPerformed(evt);
            }
        });

        jComboBoxProizvodi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProizvodiActionPerformed(evt);
            }
        });

        jLabel8.setText("Proizvod");

        jButtonDodajProizvod.setText("Dodaj proizvod");
        jButtonDodajProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajProizvodActionPerformed(evt);
            }
        });

        jLabel11.setText("Cena");

        jLabelProizvodError.setForeground(new java.awt.Color(204, 0, 0));
        jLabelProizvodError.setText("jLabel15");

        jLabel1.setText("Količina");

        jLabelKolicinaError.setForeground(new java.awt.Color(204, 0, 0));
        jLabelKolicinaError.setText("jLabel9");

        jLabel9.setText("Rabat");

        jLabel14.setText("Odeljenje i odsek");

        jComboBoxOO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOOActionPerformed(evt);
            }
        });

        jLabel15.setText("PDV");

        jComboBoxPDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20" }));

        jButtonObrisi1.setText("Ukloni proizvod");
        jButtonObrisi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisi1ActionPerformed(evt);
            }
        });

        jLabelRabatError.setForeground(new java.awt.Color(204, 0, 0));
        jLabelRabatError.setText("jLabel9");

        jLabel16.setText("%");

        jLabel17.setText("%");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jButtonDodajProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonObrisi1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(458, 458, 458)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCena, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(9, 9, 9)))
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(jComboBoxTip, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxVrsta, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBoxProizvodi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelProizvodError, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel13Layout.createSequentialGroup()
                                                .addComponent(jTextFieldKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldMernaJedinica, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabelKolicinaError, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelRabatError, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel13Layout.createSequentialGroup()
                                                .addComponent(jTextFieldRabat, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxOO, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButtonPronadjiProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(1263, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxVrsta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPronadjiProizvod))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxProizvodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelProizvodError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMernaJedinica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBoxOO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelKolicinaError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldRabat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jComboBoxPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRabatError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDodajProizvod, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonObrisi1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel12.add(jPanel13, java.awt.BorderLayout.NORTH);

        jLabel12.setText("Ukupan iznos");

        jLabel13.setText("din");

        jButtonKreirajOtpremnicu.setText("Kreiraj otpremnicu");
        jButtonKreirajOtpremnicu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajOtpremnicuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldUkupnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(36, 36, 36)
                .addComponent(jButtonKreirajOtpremnicu, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1267, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldUkupnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jButtonKreirajOtpremnicu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel12.add(jPanel14, java.awt.BorderLayout.SOUTH);

        jPanel3.add(jPanel12, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 350));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 10));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(900, 350));

        jTableStavkeOtpremnice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableStavkeOtpremnice.setShowGrid(true);
        jScrollPane2.setViewportView(jTableStavkeOtpremnice);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel9.setPreferredSize(new java.awt.Dimension(350, 50));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2235, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPronadjiKupacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPronadjiKupacActionPerformed
        if (jTextFieldKupac.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite kriterijum pretrage", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        jComboBoxFirma.removeAllItems();
        String naziv = jTextFieldKupac.getText();
        List<Kupac> lista = new ArrayList<>();
        Kupac kupac = new Kupac();
        kupac.setNaziv(naziv);
        Controller.getInstance().vratiListuSviKupac(kupac, lista);
        for (Kupac k : lista) {
            jComboBoxFirma.addItem(k);
        }
    }//GEN-LAST:event_jButtonPronadjiKupacActionPerformed

    private void jButtonOcistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOcistiActionPerformed
        if (jTextFieldKupac.getText().isEmpty()) {
            return;
        }
        List<Kupac> kupci = new ArrayList<>();
        Controller.getInstance().vratiListuKupac(kupci);
        jTextFieldKupac.setText("");
        jComboBoxFirma.removeAllItems();
        for (Kupac k : kupci) {
            jComboBoxFirma.addItem(k);
        }
    }//GEN-LAST:event_jButtonOcistiActionPerformed

    private void jButtonDodajProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajProizvodActionPerformed
        this.setValidationLabels();
        if (jTextFieldKolicina.getText().isEmpty() || jComboBoxProizvodi.getSelectedItem() == null || !jTextFieldKolicina.getText().matches("\\d+(\\.\\d+)?")) {
            jLabelKolicinaError.setText(jTextFieldKolicina.getText().isEmpty() ? "Unesite količinu" : !jTextFieldKolicina.getText().matches("\\d+(\\.\\d+)?") ? "Unesite broj" : "");
            jLabelRabatError.setText(!jTextFieldRabat.getText().matches("^\\d*$") ? "Unesite broj" : "");
            jLabelProizvodError.setText(jComboBoxProizvodi.getSelectedItem() == null ? "Izaberite proizvod" : "");
            return;
        }

        Proizvod proizvod = (Proizvod) jComboBoxProizvodi.getSelectedItem();
        double ukupnaKolicina = Double.parseDouble(jTextFieldKolicina.getText());
        double iznos = ukupnaKolicina * proizvod.getCena();
        double rabat = 0;
        if (!jTextFieldRabat.getText().isEmpty()) {
            rabat = Double.parseDouble(jTextFieldRabat.getText());
            iznos = iznos - iznos * rabat / 100;
        }
        int pdv = Integer.parseInt((String) jComboBoxPDV.getSelectedItem());
        double pdvZaSlanje = pdv;
        double iznosPdv = (pdvZaSlanje / 100) * iznos;
        double ukupnoSaPdv = iznos + iznosPdv;
        OdeljenjeOdsek oo = (OdeljenjeOdsek) jComboBoxOO.getSelectedItem();
        System.out.println(pdv);
        System.out.println(iznosPdv);

        StavkaOtpremnice so = new StavkaOtpremnice(0, otpremnica, ukupnaKolicina, iznos, rabat, pdv, iznosPdv, ukupnoSaPdv, proizvod, oo);
        StavkaOtpremniceModelTabele somt = (StavkaOtpremniceModelTabele) jTableStavkeOtpremnice.getModel();
        somt.dodajElement(so);
        sumiranaCena += iznos;
        azurirajRedneBrojeve();
    }//GEN-LAST:event_jButtonDodajProizvodActionPerformed

    private void jButtonKreirajOtpremnicuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajOtpremnicuActionPerformed
        this.setValidationLabels();
        StavkaOtpremniceModelTabele somt = (StavkaOtpremniceModelTabele) jTableStavkeOtpremnice.getModel();
        if (jComboBoxMenadzer.getSelectedItem() == null
                || jComboBoxGJ.getSelectedItem() == null
                || jComboBoxFirma.getSelectedItem() == null
                || jComboBoxOtpremac.getSelectedItem() == null
                || jComboBoxOO.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Popuniti sve podatke otpremnice", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (somt.getLista().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Otpremnica mora imati stavku", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String broj = jTextFieldBrojOtpremnice.getText();
        Menadzer menadzer = (Menadzer) jComboBoxMenadzer.getSelectedItem();
        Otpremac otpremac = (Otpremac) jComboBoxOtpremac.getSelectedItem();
        GazdinskaJedinica gj = (GazdinskaJedinica) jComboBoxGJ.getSelectedItem();
        Kupac kupac = (Kupac) jComboBoxFirma.getSelectedItem();
        java.util.Date datum = null;
        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy.");
        try {
            datum = format.parse(jTextFieldDatumOtpremnice.getText());
        } catch (ParseException ex) {
            Logger.getLogger(OtpremniceDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        Otpremnica otpremnica = new Otpremnica(broj, datum, sumiranaCena, false, menadzer, otpremac, gj, kupac);
        List<StavkaOtpremnice> listaStavki = new ArrayList<>();
        listaStavki = somt.getLista();
        if (this.otpremnica != null) {
            azurirajOtpremnicu(otpremnica, listaStavki);
            return;
        }
        boolean uspesno = Controller.getInstance().kreirajOtpremnicu(otpremnica, listaStavki);
        if (uspesno) {
            int odg = JOptionPane.showConfirmDialog(this, "Da li želite da kreirate račun za ovu otpremnicu", "Potvrda", JOptionPane.YES_NO_OPTION);
            if (odg == JOptionPane.YES_OPTION) {
                new RacunDialog(parent, true, otpremnica).setVisible(true);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Greška prilikom kreiranja otpremnice", "Greška", JOptionPane.ERROR_MESSAGE);
        }
        JOptionPane.showMessageDialog(this, "Otpremnica uspešno kreirana", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
        parent.azurirajTabelu("otpremnice");
        System.out.println(listaStavki.get(0));

        this.dispose();
    }//GEN-LAST:event_jButtonKreirajOtpremnicuActionPerformed

    private void jButtonPronadjiProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPronadjiProizvodActionPerformed
        jComboBoxProizvodi.removeAllItems();
        if (jComboBoxTip.getSelectedItem() == null && jComboBoxVrsta.getSelectedItem() == null && jComboBoxKlasa.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Unesite kriterijum pretrage", "Greška", JOptionPane.ERROR_MESSAGE);
            popuniProizvod();
            return;
        }
        Tip tip = (Tip) jComboBoxTip.getSelectedItem();
        Vrsta vrsta = (Vrsta) jComboBoxVrsta.getSelectedItem();
        Klasa klasa = (Klasa) jComboBoxKlasa.getSelectedItem();
        Proizvod proizvod = new Proizvod();
        proizvod.setTip(tip);
        proizvod.setVrsta(vrsta);
        proizvod.setKlasa(klasa);
        List<Proizvod> lista = new ArrayList<>();
        boolean uspesno = Controller.getInstance().vratiListuSviProizvod(proizvod, lista);

        if (!uspesno) {
            JOptionPane.showMessageDialog(this, "Ne postoji odgovarajući proizvod", "Upozorenje", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        for (Proizvod p : lista) {
            jComboBoxProizvodi.addItem(p);
        }
    }//GEN-LAST:event_jButtonPronadjiProizvodActionPerformed

    private void jComboBoxProizvodiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProizvodiActionPerformed
        Proizvod proizvod = (Proizvod) jComboBoxProizvodi.getSelectedItem();
        if (proizvod != null) {
            jTextFieldCena.setText(proizvod.getCena() + "");
            jTextFieldMernaJedinica.setText(proizvod.getJedinicaMere().toString());
            jComboBoxPDV.setSelectedItem(proizvod.getPdv() + "");
        } else {
            jTextFieldCena.setText("");
            jTextFieldMernaJedinica.setText("");
        }
    }//GEN-LAST:event_jComboBoxProizvodiActionPerformed

    private void jComboBoxOOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOOActionPerformed

    private void jButtonObrisi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisi1ActionPerformed
        int red = jTableStavkeOtpremnice.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Izaberite stavku otpremnice", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        StavkaOtpremniceModelTabele somt = (StavkaOtpremniceModelTabele) jTableStavkeOtpremnice.getModel();
        sumiranaCena -= somt.getLista().get(red).getIznos();
        somt.ukloniStavku(red);
        azurirajRedneBrojeve();
    }//GEN-LAST:event_jButtonObrisi1ActionPerformed

    private void jComboBoxGJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGJActionPerformed

        GazdinskaJedinica gj = (GazdinskaJedinica) jComboBoxGJ.getSelectedItem();
        List<OdeljenjeOdsek> listaOO = new ArrayList<>();
        boolean uspesno = Controller.getInstance().vratiListuOdeljenjeOdsekForGazdinskaJedinica(gj, listaOO);
        if (!uspesno) {
            JOptionPane.showMessageDialog(this, "Ne postoji odeljenje i odsek za izabranu gazdinsku jedinicu", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        jComboBoxOO.removeAllItems();
        for (OdeljenjeOdsek oo : listaOO) {
            jComboBoxOO.addItem(oo);
        }
    }//GEN-LAST:event_jComboBoxGJActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtpremniceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtpremniceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtpremniceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtpremniceDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OtpremniceDialog dialog = new OtpremniceDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajProizvod;
    private javax.swing.JButton jButtonKreirajOtpremnicu;
    private javax.swing.JButton jButtonObrisi1;
    private javax.swing.JButton jButtonOcisti;
    private javax.swing.JButton jButtonPronadjiKupac;
    private javax.swing.JButton jButtonPronadjiProizvod;
    private javax.swing.JComboBox<Kupac> jComboBoxFirma;
    private javax.swing.JComboBox<GazdinskaJedinica> jComboBoxGJ;
    private javax.swing.JComboBox<Klasa> jComboBoxKlasa;
    private javax.swing.JComboBox<Menadzer> jComboBoxMenadzer;
    private javax.swing.JComboBox<OdeljenjeOdsek> jComboBoxOO;
    private javax.swing.JComboBox<Otpremac> jComboBoxOtpremac;
    private javax.swing.JComboBox<String> jComboBoxPDV;
    private javax.swing.JComboBox<Proizvod> jComboBoxProizvodi;
    private javax.swing.JComboBox<Tip> jComboBoxTip;
    private javax.swing.JComboBox<Vrsta> jComboBoxVrsta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelKolicinaError;
    private javax.swing.JLabel jLabelProizvodError;
    private javax.swing.JLabel jLabelRabatError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableStavkeOtpremnice;
    private javax.swing.JTextField jTextFieldBrojOtpremnice;
    private javax.swing.JTextField jTextFieldCena;
    private javax.swing.JTextField jTextFieldDatumOtpremnice;
    private javax.swing.JTextField jTextFieldKolicina;
    private javax.swing.JTextField jTextFieldKupac;
    private javax.swing.JTextField jTextFieldMernaJedinica;
    private javax.swing.JTextField jTextFieldRabat;
    private javax.swing.JTextField jTextFieldUkupnaCena;
    // End of variables declaration//GEN-END:variables

    private void inicijalizacija() {
        StavkaOtpremniceModelTabele somt = new StavkaOtpremniceModelTabele(new ArrayList<>(), false);
        jTableStavkeOtpremnice.setModel(somt);
        jButtonKreirajOtpremnicu.setVisible(true);
        java.util.Date datum = new java.util.Date();
        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy.");
        String datumString = format.format(datum);

        jTextFieldDatumOtpremnice.setText(datumString);
        jTextFieldDatumOtpremnice.setEnabled(false);
        jTextFieldMernaJedinica.setEnabled(false);
        jTextFieldBrojOtpremnice.setEnabled(false);
        jTextFieldCena.setEnabled(false);
        jComboBoxMenadzer.setSelectedItem(Controller.getInstance().getUlovovani());
        jComboBoxMenadzer.setEnabled(false);
        jComboBoxPDV.setEnabled(false);
        jTextFieldUkupnaCena.setEnabled(false);
        jTextFieldMernaJedinica.setEnabled(false);

        String broj = generisiBrojOtpremnice();

        jTextFieldBrojOtpremnice.setText(broj);
        this.setValidationLabels();
    }

    private void inicijalizacija(Otpremnica otpremnica) {

        List<StavkaOtpremnice> lista = new ArrayList<>();
        boolean uspesno = Controller.getInstance().vratiListuStavkiOtpremnica(lista, otpremnica);
        if (uspesno) {
            StavkaOtpremniceModelTabele somt = new StavkaOtpremniceModelTabele(lista, otpremnica.isVerifikovana());
            jTableStavkeOtpremnice.setModel(somt);
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita listu otpremnica", "Greška", JOptionPane.ERROR_MESSAGE);
        }
        jTextFieldBrojOtpremnice.setText(otpremnica.getBroj() + "");
        jComboBoxMenadzer.setSelectedItem((Menadzer) otpremnica.getMenadzer());
        jComboBoxOtpremac.setSelectedItem((Otpremac) otpremnica.getOtpremac());

        jComboBoxGJ.setSelectedItem((GazdinskaJedinica) otpremnica.getGazdinskaJedinica());

        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy.");
        jTextFieldDatumOtpremnice.setText(format.format(otpremnica.getDatum()));
        jTextFieldDatumOtpremnice.setEnabled(false);
        jComboBoxFirma.setSelectedItem((Kupac) otpremnica.getKupac());
        jButtonKreirajOtpremnicu.setText("Ažuriraj otpremnicu");
        jTextFieldBrojOtpremnice.setEnabled(false);
        jTextFieldCena.setEnabled(false);
        jComboBoxMenadzer.setEnabled(false);
        jTextFieldUkupnaCena.setEnabled(false);
        jTextFieldMernaJedinica.setEnabled(false);
        jComboBoxPDV.setEnabled(false);
        saberiStavke();

        if (otpremnica.isVerifikovana()) {
            jPanel13.setVisible(false);
            jPanel14.setVisible(false);
            jTextFieldBrojOtpremnice.setEnabled(false);
            jComboBoxMenadzer.setEnabled(false);
            jComboBoxGJ.setEnabled(false);
            jComboBoxOtpremac.setEnabled(false);
            jButtonPronadjiKupac.setVisible(false);
            jButtonOcisti.setVisible(false);
            jTextFieldDatumOtpremnice.setEnabled(false);
            jComboBoxFirma.setEnabled(false);
            jLabel28.setVisible(false);
            jTextFieldKupac.setVisible(false);
        }

        this.setValidationLabels();

    }

    private void popuniComboBox() {
        List<Menadzer> menadzeri = new ArrayList<>();
        Controller.getInstance().vratiListuZaposlenih(menadzeri);
        List<Otpremac> otpremaci = new ArrayList<>();
        Controller.getInstance().vratiListuOtpremaca(otpremaci);
        List<GazdinskaJedinica> listaGj = new ArrayList<>();
        Controller.getInstance().vratiListuGazdinskaJedinica(listaGj);
        List<Proizvod> proizvodi = new ArrayList<>();
        Controller.getInstance().vratiListuProizvoda(proizvodi);
        Tip[] tipovi = Tip.values();
        Vrsta[] vrste = Vrsta.values();
        Klasa[] klase = Klasa.values();
        List<Kupac> kupci = new ArrayList<>();
        Controller.getInstance().vratiListuKupac(kupci);

        popuniProizvod();

        // Dodaj null na početak za svaki JComboBox
        for (Menadzer m : menadzeri) {
            jComboBoxMenadzer.addItem(m);
        }

        for (Otpremac o : otpremaci) {
            jComboBoxOtpremac.addItem(o);
        }

        for (GazdinskaJedinica gj : listaGj) {
            jComboBoxGJ.addItem(gj);
        }

        jComboBoxTip.addItem(null);
        for (Tip t : tipovi) {
            jComboBoxTip.addItem(t);
        }

        jComboBoxVrsta.addItem(null);
        for (Vrsta v : vrste) {
            jComboBoxVrsta.addItem(v);
        }
        jComboBoxVrsta.setSelectedItem(null);

        jComboBoxKlasa.addItem(null);
        for (Klasa k : klase) {
            jComboBoxKlasa.addItem(k);
        }
        jComboBoxKlasa.setSelectedItem(null);

        for (Kupac k : kupci) {
            jComboBoxFirma.addItem(k);
        }

    }

    private void popuniProizvod() {
        List<Proizvod> proizvodi = new ArrayList<>();
        Controller.getInstance().vratiListuProizvoda(proizvodi);
        jComboBoxProizvodi.addItem(null);
        for (Proizvod p : proizvodi) {
            jComboBoxProizvodi.addItem(p);
        }
        jComboBoxProizvodi.setSelectedIndex(0);
    }

    private void azurirajRedneBrojeve() {

        StavkaOtpremniceModelTabele somt = (StavkaOtpremniceModelTabele) jTableStavkeOtpremnice.getModel();

        List<StavkaOtpremnice> stavke = somt.getLista();

        for (int i = 0; i < stavke.size(); i++) {

            stavke.get(i).setRedniBroj(i + 1);

        }

        jTextFieldUkupnaCena.setText(String.format("%.3f", sumiranaCena) + "");
    }

    private void setValidationLabels() {
        jLabelKolicinaError.setText("");
        jLabelProizvodError.setText("");
        jLabelRabatError.setText("");
    }

    private void azurirajOtpremnicu(Otpremnica otpremnica, List<StavkaOtpremnice> listaStavki) {

        List<StavkaOtpremnice> stareStavke = new ArrayList<>();
        boolean uspesno = Controller.getInstance().vratiListuStavkiOtpremnica(stareStavke, otpremnica);
        if (!uspesno) {
            return;
        }
        for (StavkaOtpremnice so : stareStavke) {
            if (!listaStavki.contains(so)) {
                so.setOtpremnica(otpremnica);
                Controller.getInstance().obrisiStavkuOtpremnice(so);
            }
        }
        for (StavkaOtpremnice so : listaStavki) {
            if (!stareStavke.contains(so)) {
                so.setOtpremnica(otpremnica);
                Controller.getInstance().kreirajStavkuOtpremnice(so);
            }
        }
        Controller.getInstance().azurirajOtpremnicu(otpremnica);
        JOptionPane.showMessageDialog(this, "Uspešno ažurirana otpremnica", "Uspešno", JOptionPane.INFORMATION_MESSAGE);
        int odg = JOptionPane.showConfirmDialog(this, "Da li želite da kreirate račun za ovu otpremnicu", "Potvrda", JOptionPane.YES_NO_OPTION);
        if (odg == JOptionPane.YES_OPTION) {
            new RacunDialog(parent, true, otpremnica).setVisible(true);
        }
        parent.azurirajTabelu("otpremnice");
        this.dispose();
    }

    private String generisiBrojOtpremnice() {
        java.util.Date datum = new java.util.Date();
        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy.");
        String datumString = format.format(datum);
        String broj = datumString.substring(8, 10) + datumString.substring(3, 5) + datumString.substring(0, 2);
        List<Otpremnica> otpremnice = new ArrayList<>();
        Controller.getInstance().vratiListuOtpremnica(otpremnice);
        int poslednji = 1;
        for (Otpremnica o : otpremnice) {
            if (format.format(o.getDatum()).equals(datumString)) {
                poslednji++;
            }
        }
        broj += poslednji + "";
        return broj;
    }

    private void saberiStavke() {
        StavkaOtpremniceModelTabele somt = (StavkaOtpremniceModelTabele) jTableStavkeOtpremnice.getModel();
        for (StavkaOtpremnice so : somt.getLista()) {
            sumiranaCena += so.getIznos();
        }
        jTextFieldUkupnaCena.setText(String.format("%.3f", sumiranaCena) + "");
    }

}
