
package pogled.dialog;

import controller.Controller;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import model.Proizvod;
import model_enum.JedinicaMere;
import model_enum.Klasa;
import model_enum.Tip;
import model_enum.Vrsta;
import pogled.GlavnaForma;

/**
 *
 * @author Andrej
 */
public class ProizvodDialog extends javax.swing.JDialog {

    GlavnaForma parent = new GlavnaForma();
    Proizvod proizvod;

    /**
     * Creates new form TipDrvetaDialog
     */
    public ProizvodDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Kreiraj proizvod");
        setLocationRelativeTo(parent);
        inicijalizuj();
        setResizable(false);
        this.parent = (GlavnaForma) parent;
    }

    public ProizvodDialog(java.awt.Frame parent, boolean modal, Proizvod proizvod) {
        super(parent, modal);
        initComponents();
        setTitle("Izmeni proizvod");
        setLocationRelativeTo(parent);
        inicijalizuj(proizvod);
        this.parent = (GlavnaForma) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxTip = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxVrsta = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxKlasa = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOpis = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCena = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxMernaJedinica = new javax.swing.JComboBox<>();
        jLabelTipError = new javax.swing.JLabel();
        jLabelVrstaError = new javax.swing.JLabel();
        jLabelKlasaError = new javax.swing.JLabel();
        jLabelCenaError = new javax.swing.JLabel();
        jLabelMernaJedinicaError = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxPDV = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDatum = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonIzmeni = new javax.swing.JButton();
        jButtonSacuvajIzmene = new javax.swing.JButton();
        jButtonKreiraj = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Tip");

        jLabel2.setText("Vrsta");

        jLabel3.setText("Klasa");

        jLabel4.setText("Opis");

        jTextAreaOpis.setColumns(20);
        jTextAreaOpis.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOpis);

        jLabel5.setText("Cena");

        jLabel6.setText("Jedinica mere");

        jLabelTipError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelTipError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelTipError.setText("jLabel7");

        jLabelVrstaError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelVrstaError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelVrstaError.setText("jLabel7");

        jLabelKlasaError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelKlasaError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelKlasaError.setText("jLabel7");

        jLabelCenaError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelCenaError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelCenaError.setText("jLabel7");

        jLabelMernaJedinicaError.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelMernaJedinicaError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelMernaJedinicaError.setText("jLabel7");

        jLabel7.setText("din");

        jLabel8.setText("PDV");

        jComboBoxPDV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20" }));

        jLabel9.setText("Datum poslednje izmene");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelKlasaError, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxVrsta, javax.swing.GroupLayout.Alignment.TRAILING, 0, 372, Short.MAX_VALUE)
                                    .addComponent(jComboBoxTip, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelVrstaError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelTipError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCenaError, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldCena, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(196, 196, 196))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(jComboBoxPDV, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(291, 291, 291))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxMernaJedinica, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMernaJedinicaError, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabelTipError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxVrsta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVrstaError, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxKlasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelKlasaError, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(2, 2, 2)
                .addComponent(jLabelCenaError, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxMernaJedinica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMernaJedinicaError, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonIzmeni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonIzmeni.setText("Izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        jButtonSacuvajIzmene.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonSacuvajIzmene.setText("Sačuvaj izmene");
        jButtonSacuvajIzmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajIzmeneActionPerformed(evt);
            }
        });

        jButtonKreiraj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonKreiraj.setText("Kreiraj");
        jButtonKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajActionPerformed(evt);
            }
        });

        jButtonObrisi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonObrisi.setText("Obriši");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jButtonIzmeni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSacuvajIzmene, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(jButtonKreiraj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonObrisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonIzmeni)
                .addGap(18, 18, 18)
                .addComponent(jButtonSacuvajIzmene)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonKreiraj)
                .addGap(18, 18, 18)
                .addComponent(jButtonObrisi)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
        jComboBoxTip.setEnabled(true);
        jComboBoxVrsta.setEnabled(true);
        jComboBoxKlasa.setEnabled(true);
        jComboBoxMernaJedinica.setEnabled(true);
        jComboBoxPDV.setEnabled(true);
        jTextAreaOpis.setEnabled(true);
        jTextFieldCena.setEnabled(true);
        jButtonObrisi.setEnabled(false);
        jButtonSacuvajIzmene.setEnabled(true);
        

    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    private void jButtonKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajActionPerformed
        if (jComboBoxTip.getSelectedItem() == null
                || jComboBoxVrsta.getSelectedItem() == null
                || jComboBoxKlasa.getSelectedItem() == null
                || jTextFieldCena.getText().isEmpty()
                || !jTextFieldCena.getText().matches("\\d+(\\.\\d+)?")
                || jComboBoxMernaJedinica.getSelectedItem() == null) {
            jLabelTipError.setText(jComboBoxTip.getSelectedItem() == null ? "Unesite tip" : "");
            jLabelVrstaError.setText(jComboBoxVrsta.getSelectedItem() == null ? "Unesite vrstu" : "");
            jLabelKlasaError.setText(jComboBoxKlasa.getSelectedItem() == null ? "Unesite klasu" : "");
            jLabelCenaError.setText(jTextFieldCena.getText().isEmpty() ? "Unesite cenu" : !jTextFieldCena.getText().matches("\\d+(\\.\\d+)?") ? "Unesite broj" : "");
            jLabelMernaJedinicaError.setText(jComboBoxMernaJedinica.getSelectedItem() == null ? "Unesite mernu jedinicu" : "");
            return;
        }
        Tip tip = (Tip) jComboBoxTip.getSelectedItem();
        Vrsta vrsta = (Vrsta) jComboBoxVrsta.getSelectedItem();
        Klasa klasa = (Klasa) jComboBoxKlasa.getSelectedItem();
        double cena = Double.parseDouble(jTextFieldCena.getText());
        JedinicaMere mj = (JedinicaMere) jComboBoxMernaJedinica.getSelectedItem();
        String opis = jTextAreaOpis.getText();
        int pdv = Integer.valueOf((String) jComboBoxPDV.getSelectedItem());
        
        Proizvod proizvod = new Proizvod(WIDTH, tip, vrsta, klasa, cena, opis, mj, pdv,new java.util.Date());
        boolean uspesno = Controller.getInstance().kreirajProizvod(proizvod);
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Proizvod uspešno kreiran", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
            parent.azurirajTabelu("proizvodi");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Greška prilikom kreiranja proizvoda", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonKreirajActionPerformed

    private void jButtonSacuvajIzmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajIzmeneActionPerformed

        if (jComboBoxTip.getSelectedItem() == null
                || jComboBoxVrsta.getSelectedItem() == null
                || jComboBoxKlasa.getSelectedItem() == null
                || jTextFieldCena.getText().isEmpty()
                || !jTextFieldCena.getText().matches("\\d+(\\.\\d+)?")
                || jTextAreaOpis.getText().isEmpty()
                || jComboBoxMernaJedinica.getSelectedItem() == null) {
            jLabelTipError.setText(jComboBoxTip.getSelectedItem() == null ? "Unesite tip" : "");
            jLabelVrstaError.setText(jComboBoxVrsta.getSelectedItem() == null ? "Unesite vrstu" : "");
            jLabelKlasaError.setText(jComboBoxKlasa.getSelectedItem() == null ? "Unesite klasu" : "");
            jLabelCenaError.setText(jTextFieldCena.getText().isEmpty() ? "Unesite cenu" : !jTextFieldCena.getText().matches("\\d+(\\.\\d+)?") ? "Unesite broj" : "");
            jLabelMernaJedinicaError.setText(jComboBoxMernaJedinica.getSelectedItem() == null ? "Unesite mernu jedinicu" : "");
            return;
        }

        Tip tip = (Tip) jComboBoxTip.getSelectedItem();
        Vrsta vrsta = (Vrsta) jComboBoxVrsta.getSelectedItem();
        Klasa klasa = (Klasa) jComboBoxKlasa.getSelectedItem();
        JedinicaMere jm = (JedinicaMere) jComboBoxMernaJedinica.getSelectedItem();
        String opis = jTextAreaOpis.getText();
        double cena = Double.parseDouble(jTextFieldCena.getText());
        int pdv = Integer.valueOf((String) jComboBoxPDV.getSelectedItem());
        proizvod.setTip(tip);
        proizvod.setVrsta(vrsta);
        proizvod.setKlasa(klasa);
        proizvod.setJedinicaMere(jm);
        proizvod.setOpis(opis);
        proizvod.setCena(cena);
        proizvod.setPdv(pdv);
        proizvod.setDatumIzmene(new java.util.Date());
        boolean uspesno = Controller.getInstance().izmeniProizvod(proizvod);
        if (uspesno) {
            JOptionPane.showMessageDialog(this, "Proizvod uspešno ažuriran", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
            parent.azurirajTabelu("proizvodi");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Greška prilikom ažuriranja proizvoda", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSacuvajIzmeneActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        int odgovor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da obrišete proizvod?", "Potvrda", JOptionPane.YES_NO_OPTION);
        if (odgovor == JOptionPane.YES_OPTION) {
            boolean uspesno = Controller.getInstance().orbisiProizvod(proizvod);
            if (!uspesno) {
                JOptionPane.showMessageDialog(this, "Greška prilikom brisanja proizvoda", "Greška", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Uspešno obrisan proizvod", "Uspešno", JOptionPane.INFORMATION_MESSAGE);
                parent.azurirajTabelu("proizvodi");
                this.dispose();
            }
        }
        return;
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonKreiraj;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonSacuvajIzmene;
    private javax.swing.JComboBox<Klasa> jComboBoxKlasa;
    private javax.swing.JComboBox<JedinicaMere> jComboBoxMernaJedinica;
    private javax.swing.JComboBox<String> jComboBoxPDV;
    private javax.swing.JComboBox<Tip> jComboBoxTip;
    private javax.swing.JComboBox<Vrsta> jComboBoxVrsta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCenaError;
    private javax.swing.JLabel jLabelKlasaError;
    private javax.swing.JLabel jLabelMernaJedinicaError;
    private javax.swing.JLabel jLabelTipError;
    private javax.swing.JLabel jLabelVrstaError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaOpis;
    private javax.swing.JTextField jTextFieldCena;
    private javax.swing.JTextField jTextFieldDatum;
    // End of variables declaration//GEN-END:variables

    private void inicijalizuj() {
        popuniComboBox();
        jButtonSacuvajIzmene.setVisible(false);
        jButtonIzmeni.setVisible(false);
        jButtonObrisi.setVisible(false);

        jLabelTipError.setText("");
        jLabelVrstaError.setText("");
        jLabelKlasaError.setText("");
        jLabelCenaError.setText("");
        jLabelMernaJedinicaError.setText("");

        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy");
        jTextFieldDatum.setText(format.format(new java.util.Date()));
        jTextFieldDatum.setEnabled(false);
    }

    private void inicijalizuj(Proizvod proizvod) {
        popuniComboBox();
        jButtonKreiraj.setVisible(false);
        jButtonSacuvajIzmene.setEnabled(false);
        jComboBoxTip.setSelectedItem(proizvod.getTip());
        jComboBoxVrsta.setSelectedItem(proizvod.getVrsta());
        jComboBoxKlasa.setSelectedItem(proizvod.getKlasa());
        jComboBoxMernaJedinica.setSelectedItem(proizvod.getJedinicaMere());
        jTextAreaOpis.setText(proizvod.getOpis());
        jTextFieldCena.setText(proizvod.getCena() + "");
        jComboBoxTip.setEnabled(false);
        jComboBoxVrsta.setEnabled(false);
        jComboBoxKlasa.setEnabled(false);
        jComboBoxMernaJedinica.setEnabled(false);
        jComboBoxPDV.setEnabled(false);
        jTextAreaOpis.setEnabled(false);
        jTextFieldCena.setEnabled(false);

        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy");
        jTextFieldDatum.setText(format.format(proizvod.getDatumIzmene()));
        jTextFieldDatum.setEnabled(false);

        this.proizvod = proizvod;

        jLabelTipError.setText("");
        jLabelVrstaError.setText("");
        jLabelKlasaError.setText("");
        jLabelCenaError.setText("");
        jLabelMernaJedinicaError.setText("");
    }

    private void popuniComboBox() {
        for (Tip tip : Tip.values()) {
            jComboBoxTip.addItem(tip);
        }
        jComboBoxTip.setSelectedItem(null);
        for (Klasa klasa : Klasa.values()) {
            jComboBoxKlasa.addItem(klasa);
        }
        jComboBoxKlasa.setSelectedItem(null);

        for (Vrsta vrsta : Vrsta.values()) {
            jComboBoxVrsta.addItem(vrsta);
        }
        jComboBoxVrsta.setSelectedItem(null);

        for (JedinicaMere jm : JedinicaMere.values()) {
            jComboBoxMernaJedinica.addItem(jm);
        }
        jComboBoxMernaJedinica.setSelectedItem(null);

    }
}
